window.DRIVE_PHOTOS = [
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F20",
    "category": "Wild / field context",
    "filename": "AN2-F20WV3.HEIC",
    "caption": "Rutgers Drive — AN2-F20WV3",
    "original": "https://drive.google.com/thumbnail?id=140WEagspE1xvZCiSmm4Tq1_QISzJO1oS&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=140WEagspE1xvZCiSmm4Tq1_QISzJO1oS&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F20WV3",
    "drive_view": "https://drive.google.com/file/d/140WEagspE1xvZCiSmm4Tq1_QISzJO1oS/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F20",
    "category": "Wild / field context",
    "filename": "AN2-F20WV1.HEIC",
    "caption": "Rutgers Drive — AN2-F20WV1",
    "original": "https://drive.google.com/thumbnail?id=1IeqE97y22RTp4GEMRY0i0ulqa0D-TeB6&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1IeqE97y22RTp4GEMRY0i0ulqa0D-TeB6&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F20WV1",
    "drive_view": "https://drive.google.com/file/d/1IeqE97y22RTp4GEMRY0i0ulqa0D-TeB6/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV10.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV10",
    "original": "https://drive.google.com/thumbnail?id=1Ef-2L-u6pUMtRsnYsKuh-U5_A3BdwhXF&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1Ef-2L-u6pUMtRsnYsKuh-U5_A3BdwhXF&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV10",
    "drive_view": "https://drive.google.com/file/d/1Ef-2L-u6pUMtRsnYsKuh-U5_A3BdwhXF/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV9.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV9",
    "original": "https://drive.google.com/thumbnail?id=1XxmyMwQtZakE_vfvlF0i49fIeebN73ov&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1XxmyMwQtZakE_vfvlF0i49fIeebN73ov&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV9",
    "drive_view": "https://drive.google.com/file/d/1XxmyMwQtZakE_vfvlF0i49fIeebN73ov/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV8.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV8",
    "original": "https://drive.google.com/thumbnail?id=1hWhzEnK9xvOLGHZcbsXZ1kwxY8lPVbvU&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1hWhzEnK9xvOLGHZcbsXZ1kwxY8lPVbvU&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV8",
    "drive_view": "https://drive.google.com/file/d/1hWhzEnK9xvOLGHZcbsXZ1kwxY8lPVbvU/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV7.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV7",
    "original": "https://drive.google.com/thumbnail?id=1coi5NTWY6PO2xTbjSQKKDNJf2VJzQl0s&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1coi5NTWY6PO2xTbjSQKKDNJf2VJzQl0s&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV7",
    "drive_view": "https://drive.google.com/file/d/1coi5NTWY6PO2xTbjSQKKDNJf2VJzQl0s/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV6.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV6",
    "original": "https://drive.google.com/thumbnail?id=1dMm2kG6_bkaG3C0gCimTEbGMmot7v2F8&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1dMm2kG6_bkaG3C0gCimTEbGMmot7v2F8&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV6",
    "drive_view": "https://drive.google.com/file/d/1dMm2kG6_bkaG3C0gCimTEbGMmot7v2F8/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV5.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV5",
    "original": "https://drive.google.com/thumbnail?id=1eFoUCXws2Tcc8EeaYPXJa-nyqeVKOqNO&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1eFoUCXws2Tcc8EeaYPXJa-nyqeVKOqNO&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV5",
    "drive_view": "https://drive.google.com/file/d/1eFoUCXws2Tcc8EeaYPXJa-nyqeVKOqNO/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV4.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV4",
    "original": "https://drive.google.com/thumbnail?id=1IzOHgqL6puwYclcvquYRdIA7o5KuLz9M&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1IzOHgqL6puwYclcvquYRdIA7o5KuLz9M&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV4",
    "drive_view": "https://drive.google.com/file/d/1IzOHgqL6puwYclcvquYRdIA7o5KuLz9M/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV3.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV3",
    "original": "https://drive.google.com/thumbnail?id=1LNq2EIi7h6ZXrRk3PZRETpU_CGSaMcb-&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1LNq2EIi7h6ZXrRk3PZRETpU_CGSaMcb-&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV3",
    "drive_view": "https://drive.google.com/file/d/1LNq2EIi7h6ZXrRk3PZRETpU_CGSaMcb-/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV2.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV2",
    "original": "https://drive.google.com/thumbnail?id=1mkPT9L8mmyy6gEm1l62qjtYeKFxMhZZH&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1mkPT9L8mmyy6gEm1l62qjtYeKFxMhZZH&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV2",
    "drive_view": "https://drive.google.com/file/d/1mkPT9L8mmyy6gEm1l62qjtYeKFxMhZZH/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Wild / field context",
    "filename": "AN2-F17WV1.HEIC",
    "caption": "Rutgers Drive — AN2-F17WV1",
    "original": "https://drive.google.com/thumbnail?id=1odDrT-2BmABUfZgwY1N1BHswBc1W_0fP&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1odDrT-2BmABUfZgwY1N1BHswBc1W_0fP&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F17WV1",
    "drive_view": "https://drive.google.com/file/d/1odDrT-2BmABUfZgwY1N1BHswBc1W_0fP/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F7",
    "category": "Wild / field context",
    "filename": "AN2-F7WV2.HEIC",
    "caption": "Rutgers Drive — AN2-F7WV2",
    "original": "https://drive.google.com/thumbnail?id=1gICT3Z8zDJng9oY36nwkg-KmwY2D--il&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1gICT3Z8zDJng9oY36nwkg-KmwY2D--il&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F7WV2",
    "drive_view": "https://drive.google.com/file/d/1gICT3Z8zDJng9oY36nwkg-KmwY2D--il/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F7",
    "category": "Wild / field context",
    "filename": "AN2-F7WV1.HEIC",
    "caption": "Rutgers Drive — AN2-F7WV1",
    "original": "https://drive.google.com/thumbnail?id=1v51IFzpwZKdnLKUB60KwoMV4-RyDVbLw&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1v51IFzpwZKdnLKUB60KwoMV4-RyDVbLw&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F7WV1",
    "drive_view": "https://drive.google.com/file/d/1v51IFzpwZKdnLKUB60KwoMV4-RyDVbLw/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Wild / field context",
    "filename": "AN2-F5WV6.HEIC",
    "caption": "Rutgers Drive — AN2-F5WV6",
    "original": "https://drive.google.com/thumbnail?id=1C02plTHnGPxOFMvDjOj18YAQsE3M-21G&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1C02plTHnGPxOFMvDjOj18YAQsE3M-21G&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F5WV6",
    "drive_view": "https://drive.google.com/file/d/1C02plTHnGPxOFMvDjOj18YAQsE3M-21G/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Wild / field context",
    "filename": "AN2-F5WV5.HEIC",
    "caption": "Rutgers Drive — AN2-F5WV5",
    "original": "https://drive.google.com/thumbnail?id=1gE3pzQcI6AOZFS93nrbn8JMnAlz424PE&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1gE3pzQcI6AOZFS93nrbn8JMnAlz424PE&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F5WV5",
    "drive_view": "https://drive.google.com/file/d/1gE3pzQcI6AOZFS93nrbn8JMnAlz424PE/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Wild / field context",
    "filename": "AN2-F5WV4.HEIC",
    "caption": "Rutgers Drive — AN2-F5WV4",
    "original": "https://drive.google.com/thumbnail?id=1HXbH32Gv7wujNCiOOtBhSAzbtRU7QuAr&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1HXbH32Gv7wujNCiOOtBhSAzbtRU7QuAr&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F5WV4",
    "drive_view": "https://drive.google.com/file/d/1HXbH32Gv7wujNCiOOtBhSAzbtRU7QuAr/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Wild / field context",
    "filename": "AN2-F5WV3.HEIC",
    "caption": "Rutgers Drive — AN2-F5WV3",
    "original": "https://drive.google.com/thumbnail?id=1NVch1BwWjywGAn-8okuhqauIEcek8SSy&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1NVch1BwWjywGAn-8okuhqauIEcek8SSy&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F5WV3",
    "drive_view": "https://drive.google.com/file/d/1NVch1BwWjywGAn-8okuhqauIEcek8SSy/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Wild / field context",
    "filename": "AN2-F5WV2.HEIC",
    "caption": "Rutgers Drive — AN2-F5WV2",
    "original": "https://drive.google.com/thumbnail?id=13FVMeSXhBIFEaC31TLyHUpUAJoFlKfmZ&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=13FVMeSXhBIFEaC31TLyHUpUAJoFlKfmZ&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F5WV2",
    "drive_view": "https://drive.google.com/file/d/13FVMeSXhBIFEaC31TLyHUpUAJoFlKfmZ/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Wild / field context",
    "filename": "AN2-F5WV1.HEIC",
    "caption": "Rutgers Drive — AN2-F5WV1",
    "original": "https://drive.google.com/thumbnail?id=1aWwDPqwVO3_Krs6fhM-EdjuYr3vWKMSc&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1aWwDPqwVO3_Krs6fhM-EdjuYr3vWKMSc&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F5WV1",
    "drive_view": "https://drive.google.com/file/d/1aWwDPqwVO3_Krs6fhM-EdjuYr3vWKMSc/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F4",
    "category": "Source macro / specimen",
    "filename": "AN2-F4.HEIC",
    "caption": "Rutgers Drive — AN2-F4",
    "original": "https://drive.google.com/thumbnail?id=1_2tZiP2L1ngVnAXt-HCffEO1-bJf89hv&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1_2tZiP2L1ngVnAXt-HCffEO1-bJf89hv&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F4",
    "drive_view": "https://drive.google.com/file/d/1_2tZiP2L1ngVnAXt-HCffEO1-bJf89hv/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F3",
    "category": "Wild / field context",
    "filename": "AN2-F3V2W.HEIC",
    "caption": "Rutgers Drive — AN2-F3V2W",
    "original": "https://drive.google.com/thumbnail?id=1xTJsp9YNhCCpzMBpr4QpqrzTsQ_7an7d&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1xTJsp9YNhCCpzMBpr4QpqrzTsQ_7an7d&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F3V2W",
    "drive_view": "https://drive.google.com/file/d/1xTJsp9YNhCCpzMBpr4QpqrzTsQ_7an7d/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F3",
    "category": "Source macro / specimen",
    "filename": "AN2-F3.HEIC",
    "caption": "Rutgers Drive — AN2-F3",
    "original": "https://drive.google.com/thumbnail?id=1H53PBnnPfNQFs18vN3gSegEtXj6Mys0-&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1H53PBnnPfNQFs18vN3gSegEtXj6Mys0-&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F3",
    "drive_view": "https://drive.google.com/file/d/1H53PBnnPfNQFs18vN3gSegEtXj6Mys0-/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F3",
    "category": "Source macro / specimen",
    "filename": "AN2-F3.HEIC",
    "caption": "Rutgers Drive — AN2-F3",
    "original": "https://drive.google.com/thumbnail?id=1-b9JTz_2eHpBKBG1RW9MrS5Ojn1VqihX&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1-b9JTz_2eHpBKBG1RW9MrS5Ojn1VqihX&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F3",
    "drive_view": "https://drive.google.com/file/d/1-b9JTz_2eHpBKBG1RW9MrS5Ojn1VqihX/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V9.HEIC",
    "caption": "Rutgers Drive — AN2-F8V9",
    "original": "https://drive.google.com/thumbnail?id=1cAq7XUgEgz5bYlBbIRdIPivnzHMim1la&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1cAq7XUgEgz5bYlBbIRdIPivnzHMim1la&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V9",
    "drive_view": "https://drive.google.com/file/d/1cAq7XUgEgz5bYlBbIRdIPivnzHMim1la/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V8.HEIC",
    "caption": "Rutgers Drive — AN2-F8V8",
    "original": "https://drive.google.com/thumbnail?id=19YCY2WwSapncVPPncpk5wU7f_ab3TbH9&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=19YCY2WwSapncVPPncpk5wU7f_ab3TbH9&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V8",
    "drive_view": "https://drive.google.com/file/d/19YCY2WwSapncVPPncpk5wU7f_ab3TbH9/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V7.HEIC",
    "caption": "Rutgers Drive — AN2-F8V7",
    "original": "https://drive.google.com/thumbnail?id=1fA2NlGO6M67YQZxAeyVqE2P9nEofgUOd&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1fA2NlGO6M67YQZxAeyVqE2P9nEofgUOd&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V7",
    "drive_view": "https://drive.google.com/file/d/1fA2NlGO6M67YQZxAeyVqE2P9nEofgUOd/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V5.HEIC",
    "caption": "Rutgers Drive — AN2-F8V5",
    "original": "https://drive.google.com/thumbnail?id=1k9S90Q-ZnCdmSa991dMv_PjUxAJKG_WZ&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1k9S90Q-ZnCdmSa991dMv_PjUxAJKG_WZ&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V5",
    "drive_view": "https://drive.google.com/file/d/1k9S90Q-ZnCdmSa991dMv_PjUxAJKG_WZ/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V4.HEIC",
    "caption": "Rutgers Drive — AN2-F8V4",
    "original": "https://drive.google.com/thumbnail?id=1KYN5Qn3pQMxx60fLdsj8iOPaU4uhm4_p&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1KYN5Qn3pQMxx60fLdsj8iOPaU4uhm4_p&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V4",
    "drive_view": "https://drive.google.com/file/d/1KYN5Qn3pQMxx60fLdsj8iOPaU4uhm4_p/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V3.HEIC",
    "caption": "Rutgers Drive — AN2-F8V3",
    "original": "https://drive.google.com/thumbnail?id=1f4kFqekr5juLniG8eOCWB-_Y5MC8N_mi&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1f4kFqekr5juLniG8eOCWB-_Y5MC8N_mi&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V3",
    "drive_view": "https://drive.google.com/file/d/1f4kFqekr5juLniG8eOCWB-_Y5MC8N_mi/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V2.HEIC",
    "caption": "Rutgers Drive — AN2-F8V2",
    "original": "https://drive.google.com/thumbnail?id=1jdHsq07fiM6E1uenQGOAjKJdQlkYSD5y&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1jdHsq07fiM6E1uenQGOAjKJdQlkYSD5y&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V2",
    "drive_view": "https://drive.google.com/file/d/1jdHsq07fiM6E1uenQGOAjKJdQlkYSD5y/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V1.HEIC",
    "caption": "Rutgers Drive — AN2-F8V1",
    "original": "https://drive.google.com/thumbnail?id=1-9Y-1PdyXPQFeW5d5vUAhIKhRIKMvSEk&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1-9Y-1PdyXPQFeW5d5vUAhIKhRIKMvSEk&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F8V1",
    "drive_view": "https://drive.google.com/file/d/1-9Y-1PdyXPQFeW5d5vUAhIKhRIKMvSEk/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F7",
    "category": "Source macro / specimen",
    "filename": "AN2-F7.HEIC",
    "caption": "Rutgers Drive — AN2-F7",
    "original": "https://drive.google.com/thumbnail?id=1kyVMYcp3CiemAhnqqBv-aaOm3SPQfH3l&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1kyVMYcp3CiemAhnqqBv-aaOm3SPQfH3l&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F7",
    "drive_view": "https://drive.google.com/file/d/1kyVMYcp3CiemAhnqqBv-aaOm3SPQfH3l/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6V6.HEIC",
    "caption": "Rutgers Drive — AN2-F6V6",
    "original": "https://drive.google.com/thumbnail?id=1KchkeiArpc5ekne6ILP5d-h-buKdNufI&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1KchkeiArpc5ekne6ILP5d-h-buKdNufI&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F6V6",
    "drive_view": "https://drive.google.com/file/d/1KchkeiArpc5ekne6ILP5d-h-buKdNufI/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6V5.HEIC",
    "caption": "Rutgers Drive — AN2-F6V5",
    "original": "https://drive.google.com/thumbnail?id=1G0D4tpqRJzR05RNAh9I_oVrcdpfAp9MC&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1G0D4tpqRJzR05RNAh9I_oVrcdpfAp9MC&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F6V5",
    "drive_view": "https://drive.google.com/file/d/1G0D4tpqRJzR05RNAh9I_oVrcdpfAp9MC/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6V4.HEIC",
    "caption": "Rutgers Drive — AN2-F6V4",
    "original": "https://drive.google.com/thumbnail?id=1f8qFLr7mn7GBuBr1HkGulDOhO_1bGqFS&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1f8qFLr7mn7GBuBr1HkGulDOhO_1bGqFS&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F6V4",
    "drive_view": "https://drive.google.com/file/d/1f8qFLr7mn7GBuBr1HkGulDOhO_1bGqFS/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6V3.HEIC",
    "caption": "Rutgers Drive — AN2-F6V3",
    "original": "https://drive.google.com/thumbnail?id=1hLRjFbeH5qtqbo94KVfX5sHh-w_dyX8w&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1hLRjFbeH5qtqbo94KVfX5sHh-w_dyX8w&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F6V3",
    "drive_view": "https://drive.google.com/file/d/1hLRjFbeH5qtqbo94KVfX5sHh-w_dyX8w/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6V2.HEIC",
    "caption": "Rutgers Drive — AN2-F6V2",
    "original": "https://drive.google.com/thumbnail?id=1FEJYuLmGh-E3t0b6Nm5M5rTLJY73725P&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1FEJYuLmGh-E3t0b6Nm5M5rTLJY73725P&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F6V2",
    "drive_view": "https://drive.google.com/file/d/1FEJYuLmGh-E3t0b6Nm5M5rTLJY73725P/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6V1.HEIC",
    "caption": "Rutgers Drive — AN2-F6V1",
    "original": "https://drive.google.com/thumbnail?id=1Uzw8capGc1I4dijkGM5W_T3y3Tk5Lg9d&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1Uzw8capGc1I4dijkGM5W_T3y3Tk5Lg9d&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F6V1",
    "drive_view": "https://drive.google.com/file/d/1Uzw8capGc1I4dijkGM5W_T3y3Tk5Lg9d/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F2",
    "category": "Source macro / specimen",
    "filename": "AN2-F2V6.HEIC",
    "caption": "Rutgers Drive — AN2-F2V6",
    "original": "https://drive.google.com/thumbnail?id=1NIhboK01Lm2q5ogGSVhCOIWRwYmPK-5v&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1NIhboK01Lm2q5ogGSVhCOIWRwYmPK-5v&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F2V6",
    "drive_view": "https://drive.google.com/file/d/1NIhboK01Lm2q5ogGSVhCOIWRwYmPK-5v/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F2",
    "category": "Source macro / specimen",
    "filename": "AN2-F2V5.HEIC",
    "caption": "Rutgers Drive — AN2-F2V5",
    "original": "https://drive.google.com/thumbnail?id=1PdTwnbqTH3jR6PC4pemLybuS--YwxQTK&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1PdTwnbqTH3jR6PC4pemLybuS--YwxQTK&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F2V5",
    "drive_view": "https://drive.google.com/file/d/1PdTwnbqTH3jR6PC4pemLybuS--YwxQTK/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F2",
    "category": "Source macro / specimen",
    "filename": "AN2-F2V4.HEIC",
    "caption": "Rutgers Drive — AN2-F2V4",
    "original": "https://drive.google.com/thumbnail?id=1HT2i2nUMiu-nSuTt1WRujZ3Ire5IaaTW&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1HT2i2nUMiu-nSuTt1WRujZ3Ire5IaaTW&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F2V4",
    "drive_view": "https://drive.google.com/file/d/1HT2i2nUMiu-nSuTt1WRujZ3Ire5IaaTW/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F2",
    "category": "Source macro / specimen",
    "filename": "AN2-F2V3.HEIC",
    "caption": "Rutgers Drive — AN2-F2V3",
    "original": "https://drive.google.com/thumbnail?id=1DrJNrzuDTn0gGG5DDSefjZ0Cigf8r1Pt&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1DrJNrzuDTn0gGG5DDSefjZ0Cigf8r1Pt&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F2V3",
    "drive_view": "https://drive.google.com/file/d/1DrJNrzuDTn0gGG5DDSefjZ0Cigf8r1Pt/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F2",
    "category": "Source macro / specimen",
    "filename": "AN2-F2.HEIC",
    "caption": "Rutgers Drive — AN2-F2",
    "original": "https://drive.google.com/thumbnail?id=1Y6u6OeQHtW6TmPG39pl3YNXuTxCH7mxx&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1Y6u6OeQHtW6TmPG39pl3YNXuTxCH7mxx&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F2",
    "drive_view": "https://drive.google.com/file/d/1Y6u6OeQHtW6TmPG39pl3YNXuTxCH7mxx/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F1",
    "category": "Source macro / specimen",
    "filename": "AN2-F1V6.HEIC",
    "caption": "Rutgers Drive — AN2-F1V6",
    "original": "https://drive.google.com/thumbnail?id=1B5RxZmsVoKB5sKa171JQ8qtjXyKzRrTS&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1B5RxZmsVoKB5sKa171JQ8qtjXyKzRrTS&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F1V6",
    "drive_view": "https://drive.google.com/file/d/1B5RxZmsVoKB5sKa171JQ8qtjXyKzRrTS/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F1",
    "category": "Source macro / specimen",
    "filename": "AN2-F1V5.HEIC",
    "caption": "Rutgers Drive — AN2-F1V5",
    "original": "https://drive.google.com/thumbnail?id=1zIS81bPJaArflrHbjvuL4mEr103-LYry&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1zIS81bPJaArflrHbjvuL4mEr103-LYry&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F1V5",
    "drive_view": "https://drive.google.com/file/d/1zIS81bPJaArflrHbjvuL4mEr103-LYry/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F1",
    "category": "Source macro / specimen",
    "filename": "AN2-F1V3.HEIC",
    "caption": "Rutgers Drive — AN2-F1V3",
    "original": "https://drive.google.com/thumbnail?id=1eCvcLZHYUS9hqgh0V870Ip8p8mlspJna&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1eCvcLZHYUS9hqgh0V870Ip8p8mlspJna&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F1V3",
    "drive_view": "https://drive.google.com/file/d/1eCvcLZHYUS9hqgh0V870Ip8p8mlspJna/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F1",
    "category": "Source macro / specimen",
    "filename": "AN2-F1V2.HEIC",
    "caption": "Rutgers Drive — AN2-F1V2",
    "original": "https://drive.google.com/thumbnail?id=1zP9UrpSFrs-esMKxA-SCdN4bpjQTsiVf&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1zP9UrpSFrs-esMKxA-SCdN4bpjQTsiVf&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F1V2",
    "drive_view": "https://drive.google.com/file/d/1zP9UrpSFrs-esMKxA-SCdN4bpjQTsiVf/view"
  },
  {
    "folder": "AN2 2026",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F1",
    "category": "Source macro / specimen",
    "filename": "AN2-F1.HEIC",
    "caption": "Rutgers Drive — AN2-F1",
    "original": "https://drive.google.com/thumbnail?id=1aBdIz1Vd_Q45PWMdlpemBfvhkAk1WlRG&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1aBdIz1Vd_Q45PWMdlpemBfvhkAk1WlRG&sz=w1200",
    "source_relpath": "AN2 2026/AN2-F1",
    "drive_view": "https://drive.google.com/file/d/1aBdIz1Vd_Q45PWMdlpemBfvhkAk1WlRG/view"
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F1",
    "category": "Source macro / specimen",
    "filename": "AN2-F1.JPG",
    "caption": "Verified laboratory specimen view — AN2-F1",
    "original": "https://drive.google.com/thumbnail?id=1f6-n7J8CeSXz_8JvNVT16_xO1SzkjUlz&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1f6-n7J8CeSXz_8JvNVT16_xO1SzkjUlz&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F1.JPG",
    "drive_view": "https://drive.google.com/file/d/1f6-n7J8CeSXz_8JvNVT16_xO1SzkjUlz/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F1",
    "category": "Source macro / specimen",
    "filename": "AN2-F1V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F1V2",
    "original": "https://drive.google.com/thumbnail?id=1aoCvQW_H6lGXfH0UTe1tmhbXN50xjFdE&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1aoCvQW_H6lGXfH0UTe1tmhbXN50xjFdE&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F1V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1aoCvQW_H6lGXfH0UTe1tmhbXN50xjFdE/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F2",
    "category": "Source macro / specimen",
    "filename": "AN2-F2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F2",
    "original": "https://drive.google.com/thumbnail?id=12E4JWRMu6-q2C-gXXXsK0XnQUZDS6nUV&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=12E4JWRMu6-q2C-gXXXsK0XnQUZDS6nUV&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F2.JPG",
    "drive_view": "https://drive.google.com/file/d/12E4JWRMu6-q2C-gXXXsK0XnQUZDS6nUV/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F2",
    "category": "Source macro / specimen",
    "filename": "AN2-F2V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F2V2",
    "original": "https://drive.google.com/thumbnail?id=1xr4VtyGh1lE2xjv1uMJQWpYP0XkppfCu&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1xr4VtyGh1lE2xjv1uMJQWpYP0XkppfCu&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F2V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1xr4VtyGh1lE2xjv1uMJQWpYP0XkppfCu/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F3",
    "category": "Source macro / specimen",
    "filename": "AN2-F3.JPG",
    "caption": "Verified laboratory specimen view — AN2-F3",
    "original": "https://drive.google.com/thumbnail?id=1js47xRNUCBrHYUPbEMKggkW5mHe-16by&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1js47xRNUCBrHYUPbEMKggkW5mHe-16by&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F3.JPG",
    "drive_view": "https://drive.google.com/file/d/1js47xRNUCBrHYUPbEMKggkW5mHe-16by/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F3",
    "category": "Source macro / specimen",
    "filename": "AN2-F3V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F3V2",
    "original": "https://drive.google.com/thumbnail?id=1Lxlw8VrerbMpVnlTMXQOnECX_ooj0EYY&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1Lxlw8VrerbMpVnlTMXQOnECX_ooj0EYY&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F3V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1Lxlw8VrerbMpVnlTMXQOnECX_ooj0EYY/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F3",
    "category": "Source macro / specimen",
    "filename": "AN2-F3V3.JPG",
    "caption": "Verified laboratory specimen view — AN2-F3V3",
    "original": "https://drive.google.com/thumbnail?id=1kGqtMpKCEKePVI6iqS5_fRZnioKjN5tA&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1kGqtMpKCEKePVI6iqS5_fRZnioKjN5tA&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F3V3.JPG",
    "drive_view": "https://drive.google.com/file/d/1kGqtMpKCEKePVI6iqS5_fRZnioKjN5tA/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F3",
    "category": "Source macro / specimen",
    "filename": "AN2-F3V4.JPG",
    "caption": "Verified laboratory specimen view — AN2-F3V4",
    "original": "https://drive.google.com/thumbnail?id=1qrK7KLgNUa_NRfXcS-V5piCSphvnxkFA&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1qrK7KLgNUa_NRfXcS-V5piCSphvnxkFA&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F3V4.JPG",
    "drive_view": "https://drive.google.com/file/d/1qrK7KLgNUa_NRfXcS-V5piCSphvnxkFA/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F4",
    "category": "Source macro / specimen",
    "filename": "AN2-F4.JPG",
    "caption": "Verified laboratory specimen view — AN2-F4",
    "original": "https://drive.google.com/thumbnail?id=1W1yTOEWIpoT38jXIrQCHRu8MaQXsex56&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1W1yTOEWIpoT38jXIrQCHRu8MaQXsex56&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F4.JPG",
    "drive_view": "https://drive.google.com/file/d/1W1yTOEWIpoT38jXIrQCHRu8MaQXsex56/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F4",
    "category": "Source macro / specimen",
    "filename": "AN2-F4V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F4V2",
    "original": "https://drive.google.com/thumbnail?id=1ALI9YAGVUmES5HaosuA_TDij2Obr1b8l&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1ALI9YAGVUmES5HaosuA_TDij2Obr1b8l&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F4V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1ALI9YAGVUmES5HaosuA_TDij2Obr1b8l/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Source macro / specimen",
    "filename": "AN2-F5.JPG",
    "caption": "Verified laboratory specimen view — AN2-F5",
    "original": "https://drive.google.com/thumbnail?id=1DPHkwtounbGF1PMeBvSZjCWr0XopSSV9&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1DPHkwtounbGF1PMeBvSZjCWr0XopSSV9&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F5.JPG",
    "drive_view": "https://drive.google.com/file/d/1DPHkwtounbGF1PMeBvSZjCWr0XopSSV9/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F5",
    "category": "Source macro / specimen",
    "filename": "AN2-F5V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F5V2",
    "original": "https://drive.google.com/thumbnail?id=1Bpa2Fzgs4IWTolAGqD7GErU9lWG-Lear&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1Bpa2Fzgs4IWTolAGqD7GErU9lWG-Lear&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F5V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1Bpa2Fzgs4IWTolAGqD7GErU9lWG-Lear/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6.JPG",
    "caption": "Verified laboratory specimen view — AN2-F6",
    "original": "https://drive.google.com/thumbnail?id=17Mfq83caaha1C1xqUqsp8qfp1vG8PKKx&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=17Mfq83caaha1C1xqUqsp8qfp1vG8PKKx&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F6.JPG",
    "drive_view": "https://drive.google.com/file/d/17Mfq83caaha1C1xqUqsp8qfp1vG8PKKx/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F6",
    "category": "Source macro / specimen",
    "filename": "AN2-F6V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F6V2",
    "original": "https://drive.google.com/thumbnail?id=1ADkgP0Hb95WaM7JDhRbhei3hQh6lWicV&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1ADkgP0Hb95WaM7JDhRbhei3hQh6lWicV&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F6V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1ADkgP0Hb95WaM7JDhRbhei3hQh6lWicV/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F7",
    "category": "Source macro / specimen",
    "filename": "AN2-F7.JPG",
    "caption": "Verified laboratory specimen view — AN2-F7",
    "original": "https://drive.google.com/thumbnail?id=1IaEiwNEOSva_J1S6z1zQZtFm6JAVDyBn&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1IaEiwNEOSva_J1S6z1zQZtFm6JAVDyBn&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F7.JPG",
    "drive_view": "https://drive.google.com/file/d/1IaEiwNEOSva_J1S6z1zQZtFm6JAVDyBn/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F7",
    "category": "Source macro / specimen",
    "filename": "AN2-F7V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F7V2",
    "original": "https://drive.google.com/thumbnail?id=1bVKXop7SeKbpEzy-KWIAYIjXkUEvHJvt&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1bVKXop7SeKbpEzy-KWIAYIjXkUEvHJvt&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F7V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1bVKXop7SeKbpEzy-KWIAYIjXkUEvHJvt/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8.JPG",
    "caption": "Verified laboratory specimen view — AN2-F8",
    "original": "https://drive.google.com/thumbnail?id=1Qqg7KNVKbNUG7oLL_p53HPalaa5vceYc&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1Qqg7KNVKbNUG7oLL_p53HPalaa5vceYc&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F8.JPG",
    "drive_view": "https://drive.google.com/file/d/1Qqg7KNVKbNUG7oLL_p53HPalaa5vceYc/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F8",
    "category": "Source macro / specimen",
    "filename": "AN2-F8V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F8V2",
    "original": "https://drive.google.com/thumbnail?id=1kV3ZCbw1Ct0uKEPJnERNMCGrU10LvCQg&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1kV3ZCbw1Ct0uKEPJnERNMCGrU10LvCQg&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F8V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1kV3ZCbw1Ct0uKEPJnERNMCGrU10LvCQg/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F9",
    "category": "Source macro / specimen",
    "filename": "AN2-F9.JPG",
    "caption": "Verified laboratory specimen view — AN2-F9",
    "original": "https://drive.google.com/thumbnail?id=148GLvTrnEYcw4x5t24S_DBMuXvcZRWxS&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=148GLvTrnEYcw4x5t24S_DBMuXvcZRWxS&sz=w1200",
    "source_relpath": "AN2 2026/MycoScope Verified Lab Views 2026-09-20/AN2-F9.JPG",
    "drive_view": "https://drive.google.com/file/d/148GLvTrnEYcw4x5t24S_DBMuXvcZRWxS/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F9",
    "category": "Source macro / specimen",
    "filename": "AN2-F9V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F9V2",
    "original": "https://drive.google.com/thumbnail?id=1gdflKqU4yIjzHJCI_i_eXcKWYuxUodAh&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1gdflKqU4yIjzHJCI_i_eXcKWYuxUodAh&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F9V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1gdflKqU4yIjzHJCI_i_eXcKWYuxUodAh/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F10",
    "category": "Source macro / specimen",
    "filename": "AN2-F10.JPG",
    "caption": "Verified laboratory specimen view — AN2-F10",
    "original": "https://drive.google.com/thumbnail?id=1GrMhvJurTnTxXEDmL5oXagvEFVBeBOVt&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1GrMhvJurTnTxXEDmL5oXagvEFVBeBOVt&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F10.JPG",
    "drive_view": "https://drive.google.com/file/d/1GrMhvJurTnTxXEDmL5oXagvEFVBeBOVt/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F10",
    "category": "Source macro / specimen",
    "filename": "AN2-F10V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F10V2",
    "original": "https://drive.google.com/thumbnail?id=1HmZt5KJSQqyZwvdkYDicQPfOA2mKrvLG&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1HmZt5KJSQqyZwvdkYDicQPfOA2mKrvLG&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F10V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1HmZt5KJSQqyZwvdkYDicQPfOA2mKrvLG/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F11",
    "category": "Source macro / specimen",
    "filename": "AN2-F11.JPG",
    "caption": "Verified laboratory specimen view — AN2-F11",
    "original": "https://drive.google.com/thumbnail?id=1zOgg9gf0CoNuUyYePZvSZtSiG_PxUzeT&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1zOgg9gf0CoNuUyYePZvSZtSiG_PxUzeT&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F11.JPG",
    "drive_view": "https://drive.google.com/file/d/1zOgg9gf0CoNuUyYePZvSZtSiG_PxUzeT/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F11",
    "category": "Source macro / specimen",
    "filename": "AN2-F11V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F11V2",
    "original": "https://drive.google.com/thumbnail?id=1mv6_n6jvFxgQScFd53bmzsOJxORMQt8C&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1mv6_n6jvFxgQScFd53bmzsOJxORMQt8C&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F11V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1mv6_n6jvFxgQScFd53bmzsOJxORMQt8C/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F11",
    "category": "Source macro / specimen",
    "filename": "AN2-F11V3.JPG",
    "caption": "Verified laboratory specimen view — AN2-F11V3",
    "original": "https://drive.google.com/thumbnail?id=1qbj2p51NZlfPUzO2PB32LYZAGRK-VUYE&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1qbj2p51NZlfPUzO2PB32LYZAGRK-VUYE&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F11V3.JPG",
    "drive_view": "https://drive.google.com/file/d/1qbj2p51NZlfPUzO2PB32LYZAGRK-VUYE/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F12",
    "category": "Source macro / specimen",
    "filename": "AN2-F12.JPG",
    "caption": "Verified laboratory specimen view — AN2-F12",
    "original": "https://drive.google.com/thumbnail?id=1FMKVoK7muxRwk_VNIm2vfwAMRfNOsWhP&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1FMKVoK7muxRwk_VNIm2vfwAMRfNOsWhP&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F12.JPG",
    "drive_view": "https://drive.google.com/file/d/1FMKVoK7muxRwk_VNIm2vfwAMRfNOsWhP/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F12",
    "category": "Source macro / specimen",
    "filename": "AN2-F12V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F12V2",
    "original": "https://drive.google.com/thumbnail?id=1M7r6Cf8M5PeeIp1PtJ-_I9X_vUW49-IC&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1M7r6Cf8M5PeeIp1PtJ-_I9X_vUW49-IC&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F12V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1M7r6Cf8M5PeeIp1PtJ-_I9X_vUW49-IC/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F13",
    "category": "Source macro / specimen",
    "filename": "AN2-F13-LABEL.JPG",
    "caption": "Verified laboratory specimen view — AN2-F13-LABEL",
    "original": "https://drive.google.com/thumbnail?id=15Ip4yxROlMZI1bIzRrqhuhcUWuYTYtGA&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=15Ip4yxROlMZI1bIzRrqhuhcUWuYTYtGA&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F13-LABEL.JPG",
    "drive_view": "https://drive.google.com/file/d/15Ip4yxROlMZI1bIzRrqhuhcUWuYTYtGA/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F13",
    "category": "Source macro / specimen",
    "filename": "AN2-F13V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F13V2",
    "original": "https://drive.google.com/thumbnail?id=1oUzziduVSXC19GGH4HXo0hzICU1DRNTQ&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1oUzziduVSXC19GGH4HXo0hzICU1DRNTQ&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F13V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1oUzziduVSXC19GGH4HXo0hzICU1DRNTQ/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F13",
    "category": "Source macro / specimen",
    "filename": "AN2-F13V3.JPG",
    "caption": "Verified laboratory specimen view — AN2-F13V3",
    "original": "https://drive.google.com/thumbnail?id=17A9TeQj-JejrLNCvBrbHN9nFpJ1ReV_S&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=17A9TeQj-JejrLNCvBrbHN9nFpJ1ReV_S&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F13V3.JPG",
    "drive_view": "https://drive.google.com/file/d/17A9TeQj-JejrLNCvBrbHN9nFpJ1ReV_S/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F14",
    "category": "Source macro / specimen",
    "filename": "AN2-F14.JPG",
    "caption": "Verified laboratory specimen view — AN2-F14",
    "original": "https://drive.google.com/thumbnail?id=1ODxw6BuU8vVFfWE-r-oDoGJJ5NRr2gnE&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1ODxw6BuU8vVFfWE-r-oDoGJJ5NRr2gnE&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F14.JPG",
    "drive_view": "https://drive.google.com/file/d/1ODxw6BuU8vVFfWE-r-oDoGJJ5NRr2gnE/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F14",
    "category": "Source macro / specimen",
    "filename": "AN2-F14V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F14V2",
    "original": "https://drive.google.com/thumbnail?id=1gHJguzJTkCiiLZlFy6aTGhttdL1V4kTR&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1gHJguzJTkCiiLZlFy6aTGhttdL1V4kTR&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F14V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1gHJguzJTkCiiLZlFy6aTGhttdL1V4kTR/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F15",
    "category": "Source macro / specimen",
    "filename": "AN2-F15.JPG",
    "caption": "Verified laboratory specimen view — AN2-F15",
    "original": "https://drive.google.com/thumbnail?id=1gjyXQef7pnLKI8bJ1Vmyyu5KDjs4JYox&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1gjyXQef7pnLKI8bJ1Vmyyu5KDjs4JYox&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F15.JPG",
    "drive_view": "https://drive.google.com/file/d/1gjyXQef7pnLKI8bJ1Vmyyu5KDjs4JYox/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F15",
    "category": "Source macro / specimen",
    "filename": "AN2-F15V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F15V2",
    "original": "https://drive.google.com/thumbnail?id=1ps6b1z_v4mcWUqXTJmegUhPTOjfnyIVx&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1ps6b1z_v4mcWUqXTJmegUhPTOjfnyIVx&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F15V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1ps6b1z_v4mcWUqXTJmegUhPTOjfnyIVx/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F16",
    "category": "Source macro / specimen",
    "filename": "AN2-F16.JPG",
    "caption": "Verified laboratory specimen view — AN2-F16",
    "original": "https://drive.google.com/thumbnail?id=1jsbA5A5Xf2jGnczrUXpPdcto1lMt9Hjq&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1jsbA5A5Xf2jGnczrUXpPdcto1lMt9Hjq&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F16.JPG",
    "drive_view": "https://drive.google.com/file/d/1jsbA5A5Xf2jGnczrUXpPdcto1lMt9Hjq/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F16",
    "category": "Source macro / specimen",
    "filename": "AN2-F16V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F16V2",
    "original": "https://drive.google.com/thumbnail?id=1O_phydkPUBwIsSY5SxpsBKRGXNKRk-m_&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1O_phydkPUBwIsSY5SxpsBKRGXNKRk-m_&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F16V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1O_phydkPUBwIsSY5SxpsBKRGXNKRk-m_/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Source macro / specimen",
    "filename": "AN2-F17.JPG",
    "caption": "Verified laboratory specimen view — AN2-F17",
    "original": "https://drive.google.com/thumbnail?id=1m0QOFfuWkbbe-faxU1fDZq0rMCTPvH7D&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1m0QOFfuWkbbe-faxU1fDZq0rMCTPvH7D&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F17.JPG",
    "drive_view": "https://drive.google.com/file/d/1m0QOFfuWkbbe-faxU1fDZq0rMCTPvH7D/view",
    "verified_label": true
  },
  {
    "folder": "AN2 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "AN2",
    "family": "AN",
    "specimen": "AN2-F17",
    "category": "Source macro / specimen",
    "filename": "AN2-F17V2.JPG",
    "caption": "Verified laboratory specimen view — AN2-F17V2",
    "original": "https://drive.google.com/thumbnail?id=1gxQZvvbzNTBdneE4S3uVkC27ZklJemKo&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1gxQZvvbzNTBdneE4S3uVkC27ZklJemKo&sz=w1200",
    "source_relpath": "AN2 verified lab views/AN2-F17V2.JPG",
    "drive_view": "https://drive.google.com/file/d/1gxQZvvbzNTBdneE4S3uVkC27ZklJemKo/view",
    "verified_label": true
  },
  {
    "folder": "JN1 2026/MycoScope Verified Lab Views 2026-09-20",
    "collection": "JN1",
    "family": "JN",
    "specimen": "JN1-F11",
    "category": "Source macro / specimen",
    "filename": "JN1-F11-LAB.JPG",
    "caption": "Verified laboratory specimen view — JN1-F11-LAB",
    "original": "https://drive.google.com/thumbnail?id=1jNBSyTaoxsv9_PgZSZIYJkqQo3BcILKP&sz=w2400",
    "thumb": "https://drive.google.com/thumbnail?id=1jNBSyTaoxsv9_PgZSZIYJkqQo3BcILKP&sz=w1200",
    "source_relpath": "JN1 verified lab views/JN1-F11-LAB.JPG",
    "drive_view": "https://drive.google.com/file/d/1jNBSyTaoxsv9_PgZSZIYJkqQo3BcILKP/view",
    "verified_label": true
  }
];
