window.DRIVE_PHOTOS = window.DRIVE_PHOTOS || [];
window.DRIVE_PHOTOS.push(
  {"folder":"JN1 lab additions","collection":"JN1","family":"JN","specimen":"JN1-F1","category":"Spore print / preparation","filename":"JN1-F1SP.JPG","caption":"JN1-F1 — spore-print / preparation documentation","id":"186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-","original":"https://drive.google.com/thumbnail?id=186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-&sz=w1200","source_relpath":"JN1 lab additions/JN1-F1SP.JPG","drive_view":"https://drive.google.com/file/d/186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Spore print / preparation","filename":"AN2-25SP.JPG","caption":"AN2-F25 — spore-print / preparation documentation (foil label reads AN2 25)","id":"1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx","original":"https://drive.google.com/thumbnail?id=1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx&sz=w1200","source_relpath":"AN2 lab additions/AN2-25SP.JPG","drive_view":"https://drive.google.com/file/d/1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F3","category":"Spore print / preparation","filename":"AN2-F3SP.JPG","caption":"AN2-F3 — spore-print documentation","id":"1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB","original":"https://drive.google.com/thumbnail?id=1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB&sz=w1200","source_relpath":"AN2 lab additions/AN2-F3SP.JPG","drive_view":"https://drive.google.com/file/d/1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F6","category":"Spore print / preparation","filename":"AN2-F6SP.JPG","caption":"AN2-F6 — spore-print / preparation documentation","id":"1qN99QPdNFLd84kkw29sdssdvSYyEX1lt","original":"https://drive.google.com/thumbnail?id=1qN99QPdNFLd84kkw29sdssdvSYyEX1lt&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1qN99QPdNFLd84kkw29sdssdvSYyEX1lt&sz=w1200","source_relpath":"AN2 lab additions/AN2-F6SP.JPG","drive_view":"https://drive.google.com/file/d/1qN99QPdNFLd84kkw29sdssdvSYyEX1lt/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F8","category":"Spore print / preparation","filename":"AN2-F8SP.JPG","caption":"AN2-F8 — spore-print / preparation documentation","id":"16ynn2bPt3Yup07dZBOLr43CnbRxUTypP","original":"https://drive.google.com/thumbnail?id=16ynn2bPt3Yup07dZBOLr43CnbRxUTypP&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=16ynn2bPt3Yup07dZBOLr43CnbRxUTypP&sz=w1200","source_relpath":"AN2 lab additions/AN2-F8SP.JPG","drive_view":"https://drive.google.com/file/d/16ynn2bPt3Yup07dZBOLr43CnbRxUTypP/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F13","category":"Spore print / preparation","filename":"AN2-F13.JPG","caption":"AN2-F13 — lab preparation documentation","id":"17bYluAWMThymL9eQ1eyHeDrVcLcTQveM","original":"https://drive.google.com/thumbnail?id=17bYluAWMThymL9eQ1eyHeDrVcLcTQveM&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=17bYluAWMThymL9eQ1eyHeDrVcLcTQveM&sz=w1200","source_relpath":"AN2 lab additions/AN2-F13.JPG","drive_view":"https://drive.google.com/file/d/17bYluAWMThymL9eQ1eyHeDrVcLcTQveM/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F21","category":"Spore print / preparation","filename":"AN2-F21 SPOREPRINT.JPG","caption":"AN2-F21 — spore print","id":"1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3","original":"https://drive.google.com/thumbnail?id=1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3&sz=w1200","source_relpath":"AN2 lab additions/AN2-F21 SPOREPRINT.JPG","drive_view":"https://drive.google.com/file/d/1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Spore print / preparation","filename":"AN2-F25SP.JPG","caption":"AN2-F25 — spore-print / preparation documentation","id":"16x_mrY3-geK1LqGvQBEAAUODHen_j4VU","original":"https://drive.google.com/thumbnail?id=16x_mrY3-geK1LqGvQBEAAUODHen_j4VU&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=16x_mrY3-geK1LqGvQBEAAUODHen_j4VU&sz=w1200","source_relpath":"AN2 lab additions/AN2-F25SP.JPG","drive_view":"https://drive.google.com/file/d/16x_mrY3-geK1LqGvQBEAAUODHen_j4VU/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F31","category":"Spore print / preparation","filename":"AN2-F31SP.JPG","caption":"AN2-F31 — spore-print documentation","id":"1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d","original":"https://drive.google.com/thumbnail?id=1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d&sz=w1200","source_relpath":"AN2 lab additions/AN2-F31SP.JPG","drive_view":"https://drive.google.com/file/d/1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F31","category":"Spore print / preparation","filename":"AN2-F31SPV2.JPG","caption":"AN2-F31 — spore-print documentation, view 2","id":"1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd","original":"https://drive.google.com/thumbnail?id=1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd&sz=w1200","source_relpath":"AN2 lab additions/AN2-F31SPV2.JPG","drive_view":"https://drive.google.com/file/d/1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F32","category":"Spore print / preparation","filename":"AN2-F32SP.JPG","caption":"AN2-F32 — spore-print documentation","id":"1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT","original":"https://drive.google.com/thumbnail?id=1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT&sz=w1200","source_relpath":"AN2 lab additions/AN2-F32SP.JPG","drive_view":"https://drive.google.com/file/d/1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F34","category":"Spore print / preparation","filename":"AN2-F34SP.JPG","caption":"AN2-F34 — spore-print documentation","id":"1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh","original":"https://drive.google.com/thumbnail?id=1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh&sz=w1200","source_relpath":"AN2 lab additions/AN2-F34SP.JPG","drive_view":"https://drive.google.com/file/d/1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F36","category":"Spore print / preparation","filename":"AN2-F36SP.JPG","caption":"AN2-F36 — spore-print / preparation documentation","id":"1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze","original":"https://drive.google.com/thumbnail?id=1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze&sz=w1200","source_relpath":"AN2 lab additions/AN2-F36SP.JPG","drive_view":"https://drive.google.com/file/d/1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F38","category":"Spore print / preparation","filename":"AN2-F38SP.JPG","caption":"AN2-F38 — spore-print / preparation documentation","id":"1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2","original":"https://drive.google.com/thumbnail?id=1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2&sz=w1200","source_relpath":"AN2 lab additions/AN2-F38SP.JPG","drive_view":"https://drive.google.com/file/d/1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F40","category":"Spore print / preparation","filename":"AN2-F40SP.JPG","caption":"AN2-F40 — spore-print / preparation documentation","id":"1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As","original":"https://drive.google.com/thumbnail?id=1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As&sz=w1200","source_relpath":"AN2 lab additions/AN2-F40SP.JPG","drive_view":"https://drive.google.com/file/d/1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Spore print / preparation","filename":"AN2-F41SP.JPG","caption":"AN2-F41 — spore-print / preparation documentation","id":"1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c","original":"https://drive.google.com/thumbnail?id=1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41SP.JPG","drive_view":"https://drive.google.com/file/d/1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c/view"},
  {"folder":"JN1 lab additions","collection":"JN1","family":"JN","specimen":"JN1-F19","category":"Spore print / preparation","filename":"JN1-19SP.JPG","caption":"JN1-F19 — spore-print / preparation documentation (foil label identifies JN1 F19)","id":"1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn","original":"https://drive.google.com/thumbnail?id=1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn&sz=w1200","source_relpath":"JN1 lab additions/JN1-19SP.JPG","drive_view":"https://drive.google.com/file/d/1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"IMG_0904.JPG","caption":"Behind the scenes — uncatalogued lab/workbench photograph; no specimen accession assigned","id":"1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j","original":"https://drive.google.com/thumbnail?id=1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j&sz=w1200","source_relpath":"Behind the Scenes - Extras/IMG_0904.JPG","drive_view":"https://drive.google.com/file/d/1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"JEANKARMAV1.JPG","caption":"Behind the scenes — lab collection handling","id":"1j3r3r1sOWk_IChKomEQRRirin0A2lFja","original":"https://drive.google.com/thumbnail?id=1j3r3r1sOWk_IChKomEQRRirin0A2lFja&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1j3r3r1sOWk_IChKomEQRRirin0A2lFja&sz=w1200","source_relpath":"Behind the Scenes - Extras/JEANKARMAV1.JPG","drive_view":"https://drive.google.com/file/d/1j3r3r1sOWk_IChKomEQRRirin0A2lFja/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"JEANV1.JPG","caption":"Behind the scenes — lab collection handling","id":"1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC","original":"https://drive.google.com/thumbnail?id=1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC&sz=w1200","source_relpath":"Behind the Scenes - Extras/JEANV1.JPG","drive_view":"https://drive.google.com/file/d/1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC/view"},
  {"folder":"JN1 lab additions","collection":"JN1","family":"JN","specimen":"JN1-F32","category":"Spore print / preparation","filename":"JN1-F32SP.JPG","caption":"JN1-F32 — spore-print / preparation documentation","id":"12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w","original":"https://drive.google.com/thumbnail?id=12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w&sz=w1200","source_relpath":"JN1 lab additions/JN1-F32SP.JPG","drive_view":"https://drive.google.com/file/d/12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"KARMAAA.JPG","caption":"Behind the scenes — lab companion / candid photograph; no fungal specimen accession assigned","id":"1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti","original":"https://drive.google.com/thumbnail?id=1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti&sz=w1200","source_relpath":"Behind the Scenes - Extras/KARMAAA.JPG","drive_view":"https://drive.google.com/file/d/1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (9).png","caption":"AN2-F9 — microscopy, spore-mount field view","id":"1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR","original":"https://drive.google.com/thumbnail?id=1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (9).png","drive_view":"https://drive.google.com/file/d/1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (10).png","caption":"AN2-F9 — annotated microscopy measurements, calibrated spore-mount field","id":"1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN","original":"https://drive.google.com/thumbnail?id=1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (10).png","drive_view":"https://drive.google.com/file/d/1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (1).png","caption":"AN2-F9 — annotated microscopy measurements, calibrated spore-mount field","id":"1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE","original":"https://drive.google.com/thumbnail?id=1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (1).png","drive_view":"https://drive.google.com/file/d/1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (2).png","caption":"AN2-F9 — annotated microscopy measurements, calibrated spore-mount field","id":"1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0","original":"https://drive.google.com/thumbnail?id=1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (2).png","drive_view":"https://drive.google.com/file/d/1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (5).png","caption":"AN2-F9 — microscopy, dense spore-mount field","id":"1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9","original":"https://drive.google.com/thumbnail?id=1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (5).png","drive_view":"https://drive.google.com/file/d/1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (7).png","caption":"AN2-F9 — microscopy, spore-mount field view","id":"1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg","original":"https://drive.google.com/thumbnail?id=1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (7).png","drive_view":"https://drive.google.com/file/d/1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (8).png","caption":"AN2-F9 — microscopy, dense spore-mount field view","id":"1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD","original":"https://drive.google.com/thumbnail?id=1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (8).png","drive_view":"https://drive.google.com/file/d/1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Spore print / preparation","filename":"IMG_2026-09-30-16-09-14-953.jpg","caption":"AN2-F9 — labeled slide / foil preparation documentation","id":"1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC","original":"https://drive.google.com/thumbnail?id=1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC&sz=w1200","source_relpath":"AN2 lab additions/IMG_2026-09-30-16-09-14-953.jpg","drive_view":"https://drive.google.com/file/d/1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Spore print / preparation","filename":"IMG_2026-09-30-16-09-11-416.jpg","caption":"AN2-F9 — labeled slide / foil preparation documentation, view 2","id":"1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y","original":"https://drive.google.com/thumbnail?id=1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y&sz=w1200","source_relpath":"AN2 lab additions/IMG_2026-09-30-16-09-11-416.jpg","drive_view":"https://drive.google.com/file/d/1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y/view"}
);

window.SPECIMEN_ENRICHMENTS = window.SPECIMEN_ENRICHMENTS || {};
window.SPECIMEN_ENRICHMENTS["AN2-F9"] = {
  status: "AN2-F9 laboratory dataset — microscopy and preparation imagery integrated; field/master dossier remains separate.",
  sourceLine: "Rutgers Extension laboratory accession AN2-F9. Assignment is supported by explicit AN2-F9 filenames and visible AN2 F9 labeling in the preparation photographs. Measurement statistics use only fully legible on-image annotations; obscured labels were excluded rather than inferred.",
  summary: {
    "Record type": "Curated AN2 laboratory microscopy accession",
    "Provenance": "Rutgers Extension / AN2-F9 laboratory imaging, 2026-09-30",
    "Laboratory media": "7 microscopy frames + 2 labeled preparation photographs",
    "Microscopy observation": "Numerous small rounded to subglobose bodies are visible, commonly clustered in the mounted material.",
    "Readable measurement set": "37 fully legible calibrated annotations across 3 measured microscopy frames",
    "Measured range": "1.75–3.27 µm",
    "Measured mean": "2.54 µm",
    "Measured median": "2.59 µm",
    "Measurement handling": "One partially obscured annotation was excluded; no hidden value was guessed."
  },
  completeness: [
    ["Photo provenance","Yes"],
    ["Explicit specimen accession","Yes"],
    ["Preparation imagery","Yes"],
    ["Microscopy imagery","Yes"],
    ["Calibrated measurement annotations","Yes"],
    ["Master field dossier present","No"]
  ]
};
