window.DRIVE_PHOTOS = window.DRIVE_PHOTOS || [];
window.DRIVE_PHOTOS.push(
  {"folder":"JN1 lab additions","collection":"JN1","family":"JN","specimen":"JN1-F1","category":"Spore print / preparation","filename":"JN1-F1SP.JPG","caption":"JN1-F1 — spore-print / preparation documentation","id":"186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-","original":"https://drive.google.com/thumbnail?id=186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-&sz=w1200","source_relpath":"JN1 lab additions/JN1-F1SP.JPG","drive_view":"https://drive.google.com/file/d/186rSqsx8-xM-pNzASTPo_mA9O4s9DHF-/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Spore print / preparation","filename":"AN2-25SP.JPG","caption":"AN2-F25 — spore-print / preparation documentation (foil label reads AN2 25)","id":"1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx","original":"https://drive.google.com/thumbnail?id=1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx&sz=w1200","source_relpath":"AN2 lab additions/AN2-25SP.JPG","drive_view":"https://drive.google.com/file/d/1f-qbDOoqwQe8qaOWY1IRCj4fEzs7loXx/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F3","category":"Spore print / preparation","filename":"AN2-F3SP.JPG","caption":"AN2-F3 — spore-print documentation","id":"1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB","original":"https://drive.google.com/thumbnail?id=1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB&sz=w1200","source_relpath":"AN2 lab additions/AN2-F3SP.JPG","drive_view":"https://drive.google.com/file/d/1tn5jp5MpHcr7mzh8JKJeQoBu0MSCAJxB/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F6","category":"Spore print / preparation","filename":"AN2-F6SP.JPG","caption":"AN2-F6 — spore-print / preparation documentation","id":"1qN99QPdNFLd84kkw29sdssdvSYyEX1lt","original":"https://drive.google.com/thumbnail?id=1qN99QPdNFLd84kkw29sdssdvSYyEX1lt&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1qN99QPdNFLd84kkw29sdssdvSYyEX1lt&sz=w1200","source_relpath":"AN2 lab additions/AN2-F6SP.JPG","drive_view":"https://drive.google.com/file/d/1qN99QPdNFLd84kkw29sdssdvSYyEX1lt/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F8","category":"Spore print / preparation","filename":"AN2-F8SP.JPG","caption":"AN2-F8 — spore-print / preparation documentation","id":"16ynn2bPt3Yup07dZBOLr43CnbRxUTypP","original":"https://drive.google.com/thumbnail?id=16ynn2bPt3Yup07dZBOLr43CnbRxUTypP&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=16ynn2bPt3Yup07dZBOLr43CnbRxUTypP&sz=w1200","source_relpath":"AN2 lab additions/AN2-F8SP.JPG","drive_view":"https://drive.google.com/file/d/16ynn2bPt3Yup07dZBOLr43CnbRxUTypP/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F13","category":"Spore print / preparation","filename":"AN2-F13.JPG","caption":"AN2-F13 — lab preparation documentation","id":"17bYluAWMThymL9eQ1eyHeDrVcLcTQveM","original":"https://drive.google.com/thumbnail?id=17bYluAWMThymL9eQ1eyHeDrVcLcTQveM&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=17bYluAWMThymL9eQ1eyHeDrVcLcTQveM&sz=w1200","source_relpath":"AN2 lab additions/AN2-F13.JPG","drive_view":"https://drive.google.com/file/d/17bYluAWMThymL9eQ1eyHeDrVcLcTQveM/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F21","category":"Spore print / preparation","filename":"AN2-F21 SPOREPRINT.JPG","caption":"AN2-F21 — spore print","id":"1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3","original":"https://drive.google.com/thumbnail?id=1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3&sz=w1200","source_relpath":"AN2 lab additions/AN2-F21 SPOREPRINT.JPG","drive_view":"https://drive.google.com/file/d/1-HhIR9lO7mCkWz7hHwoDMv_V0yVnZ0v3/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Spore print / preparation","filename":"AN2-F25SP.JPG","caption":"AN2-F25 — spore-print / preparation documentation","id":"16x_mrY3-geK1LqGvQBEAAUODHen_j4VU","original":"https://drive.google.com/thumbnail?id=16x_mrY3-geK1LqGvQBEAAUODHen_j4VU&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=16x_mrY3-geK1LqGvQBEAAUODHen_j4VU&sz=w1200","source_relpath":"AN2 lab additions/AN2-F25SP.JPG","drive_view":"https://drive.google.com/file/d/16x_mrY3-geK1LqGvQBEAAUODHen_j4VU/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F31","category":"Spore print / preparation","filename":"AN2-F31SP.JPG","caption":"AN2-F31 — spore-print documentation","id":"1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d","original":"https://drive.google.com/thumbnail?id=1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d&sz=w1200","source_relpath":"AN2 lab additions/AN2-F31SP.JPG","drive_view":"https://drive.google.com/file/d/1sloxtCSJtqR_7dZgRU74aAeFSQlmKa7d/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F31","category":"Spore print / preparation","filename":"AN2-F31SPV2.JPG","caption":"AN2-F31 — spore-print documentation, view 2","id":"1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd","original":"https://drive.google.com/thumbnail?id=1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd&sz=w1200","source_relpath":"AN2 lab additions/AN2-F31SPV2.JPG","drive_view":"https://drive.google.com/file/d/1aTTWus3ca4Fu6EEiVUsDOLySiEcfPMnd/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F32","category":"Spore print / preparation","filename":"AN2-F32SP.JPG","caption":"AN2-F32 — spore-print documentation","id":"1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT","original":"https://drive.google.com/thumbnail?id=1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT&sz=w1200","source_relpath":"AN2 lab additions/AN2-F32SP.JPG","drive_view":"https://drive.google.com/file/d/1mJjbwtA44gPVKMiTL1U-7yIyZHL32ijT/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F34","category":"Spore print / preparation","filename":"AN2-F34SP.JPG","caption":"AN2-F34 — spore-print documentation","id":"1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh","original":"https://drive.google.com/thumbnail?id=1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh&sz=w1200","source_relpath":"AN2 lab additions/AN2-F34SP.JPG","drive_view":"https://drive.google.com/file/d/1qQ-Ta4K4rAyUURRrxEqelDWi1sQptMQh/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F36","category":"Spore print / preparation","filename":"AN2-F36SP.JPG","caption":"AN2-F36 — spore-print / preparation documentation","id":"1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze","original":"https://drive.google.com/thumbnail?id=1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze&sz=w1200","source_relpath":"AN2 lab additions/AN2-F36SP.JPG","drive_view":"https://drive.google.com/file/d/1sXTbMZGP0dW4p71ck72fjFPI--Nu96Ze/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F38","category":"Spore print / preparation","filename":"AN2-F38SP.JPG","caption":"AN2-F38 — spore-print / preparation documentation","id":"1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2","original":"https://drive.google.com/thumbnail?id=1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2&sz=w1200","source_relpath":"AN2 lab additions/AN2-F38SP.JPG","drive_view":"https://drive.google.com/file/d/1d39iuekBXZY1Jz--tDwDYokLyPw-1Qw2/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F40","category":"Spore print / preparation","filename":"AN2-F40SP.JPG","caption":"AN2-F40 — spore-print / preparation documentation","id":"1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As","original":"https://drive.google.com/thumbnail?id=1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As&sz=w1200","source_relpath":"AN2 lab additions/AN2-F40SP.JPG","drive_view":"https://drive.google.com/file/d/1CEO2rLM18VBfQBmbNoN7W8LZEb3Vj2As/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Spore print / preparation","filename":"AN2-F41SP.JPG","caption":"AN2-F41 — spore-print / preparation documentation","id":"1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c","original":"https://drive.google.com/thumbnail?id=1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41SP.JPG","drive_view":"https://drive.google.com/file/d/1NrEsa6OHKdimAiY7qTZZul9X1ZGP6p2c/view"},
  {"folder":"JN1 lab additions","collection":"JN1","family":"JN","specimen":"JN1-F19","category":"Spore print / preparation","filename":"JN1-19SP.JPG","caption":"JN1-F19 — spore-print / preparation documentation (foil label identifies JN1 F19)","id":"1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn","original":"https://drive.google.com/thumbnail?id=1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn&sz=w1200","source_relpath":"JN1 lab additions/JN1-19SP.JPG","drive_view":"https://drive.google.com/file/d/1vwtppl5vLpeMwez3eNyYV4OOIVYQ8wyn/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"IMG_0904.JPG","caption":"Behind the scenes — uncatalogued lab/workbench photograph; no specimen accession assigned","id":"1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j","original":"https://drive.google.com/thumbnail?id=1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j&sz=w1200","source_relpath":"Behind the Scenes - Extras/IMG_0904.JPG","drive_view":"https://drive.google.com/file/d/1Yll9B7MkHqXXg1fN0AHXLszJ1HGSqN8j/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"JEANKARMAV1.JPG","caption":"Behind the scenes — lab collection handling","id":"1j3r3r1sOWk_IChKomEQRRirin0A2lFja","original":"https://drive.google.com/thumbnail?id=1j3r3r1sOWk_IChKomEQRRirin0A2lFja&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1j3r3r1sOWk_IChKomEQRRirin0A2lFja&sz=w1200","source_relpath":"Behind the Scenes - Extras/JEANKARMAV1.JPG","drive_view":"https://drive.google.com/file/d/1j3r3r1sOWk_IChKomEQRRirin0A2lFja/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"JEANV1.JPG","caption":"Behind the scenes — lab collection handling","id":"1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC","original":"https://drive.google.com/thumbnail?id=1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC&sz=w1200","source_relpath":"Behind the Scenes - Extras/JEANV1.JPG","drive_view":"https://drive.google.com/file/d/1y7tZ8_IQ5DpvA-lDcN8avyhBmJauGrNC/view"},
  {"folder":"JN1 lab additions","collection":"JN1","family":"JN","specimen":"JN1-F32","category":"Spore print / preparation","filename":"JN1-F32SP.JPG","caption":"JN1-F32 — spore-print / preparation documentation","id":"12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w","original":"https://drive.google.com/thumbnail?id=12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w&sz=w1200","source_relpath":"JN1 lab additions/JN1-F32SP.JPG","drive_view":"https://drive.google.com/file/d/12ASb-32OR3VPiBdrSMcoPPq7Jegm1n0w/view"},
  {"folder":"Behind the Scenes - Extras","collection":"Extras","family":"EX","specimen":"BEHIND-THE-SCENES","category":"Behind the scenes / extras","filename":"KARMAAA.JPG","caption":"Behind the scenes — lab companion / candid photograph; no fungal specimen accession assigned","id":"1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti","original":"https://drive.google.com/thumbnail?id=1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti&sz=w1200","source_relpath":"Behind the Scenes - Extras/KARMAAA.JPG","drive_view":"https://drive.google.com/file/d/1XpuRBU6fb8qz9ck16rA27dSjpbUMf9ti/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (9).png","caption":"AN2-F9 — microscopy, spore-mount field view","id":"1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR","original":"https://drive.google.com/thumbnail?id=1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (9).png","drive_view":"https://drive.google.com/file/d/1Tpu0he3d-nMdl43Tqw4Pp1dHBRrxYvLR/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (10).png","caption":"AN2-F9 — annotated microscopy measurements, calibrated spore-mount field","id":"1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN","original":"https://drive.google.com/thumbnail?id=1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (10).png","drive_view":"https://drive.google.com/file/d/1UlqBRZfynqNZQAZn6zA8ZpDUwirtkUGN/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (1).png","caption":"AN2-F9 — annotated microscopy measurements, calibrated spore-mount field","id":"1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE","original":"https://drive.google.com/thumbnail?id=1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (1).png","drive_view":"https://drive.google.com/file/d/1-E62YSCjfcFHl7yWZ7n5nT4eQEhWQBuE/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (2).png","caption":"AN2-F9 — annotated microscopy measurements, calibrated spore-mount field","id":"1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0","original":"https://drive.google.com/thumbnail?id=1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (2).png","drive_view":"https://drive.google.com/file/d/1WBWJI9GTg_2g5JXfmAYPZ0CnOyGg50r0/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (5).png","caption":"AN2-F9 — microscopy, dense spore-mount field","id":"1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9","original":"https://drive.google.com/thumbnail?id=1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (5).png","drive_view":"https://drive.google.com/file/d/1px_m_amZK6VO9ZdNoRLV02JFv-rllVh9/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (7).png","caption":"AN2-F9 — microscopy, spore-mount field view","id":"1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg","original":"https://drive.google.com/thumbnail?id=1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (7).png","drive_view":"https://drive.google.com/file/d/1U8Eb80yTYaBDJLbPvWdjjEvZeMNrt-Zg/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Microscopy","filename":"AN2-F9 SPMV1 (8).png","caption":"AN2-F9 — microscopy, dense spore-mount field view","id":"1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD","original":"https://drive.google.com/thumbnail?id=1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD&sz=w1200","source_relpath":"AN2 lab additions/AN2-F9 SPMV1 (8).png","drive_view":"https://drive.google.com/file/d/1PcD-u-mGSBw-AKAJqgqNLL9ve8OnkjAD/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Spore print / preparation","filename":"IMG_2026-09-30-16-09-14-953.jpg","caption":"AN2-F9 — labeled slide / foil preparation documentation","id":"1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC","original":"https://drive.google.com/thumbnail?id=1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC&sz=w1200","source_relpath":"AN2 lab additions/IMG_2026-09-30-16-09-14-953.jpg","drive_view":"https://drive.google.com/file/d/1OX2ZJDgk6rlabVtwFvYfCyZycgUtQ9tC/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Spore print / preparation","filename":"IMG_2026-09-30-16-09-11-416.jpg","caption":"AN2-F9 — labeled slide / foil preparation documentation, view 2","id":"1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y","original":"https://drive.google.com/thumbnail?id=1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y&sz=w1200","source_relpath":"AN2 lab additions/IMG_2026-09-30-16-09-11-416.jpg","drive_view":"https://drive.google.com/file/d/1A32AVdGLt1aLYbk-JnQiQz4TifsfjO0y/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Wild / field context","filename":"IMG_6004.jpg","caption":"AN2-F9 — wild field context, hymenophore close-up on wood","id":"18BgujAIi7bwre-YJSkPJLzracA1_6WEo","original":"https://drive.google.com/thumbnail?id=18BgujAIi7bwre-YJSkPJLzracA1_6WEo&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=18BgujAIi7bwre-YJSkPJLzracA1_6WEo&sz=w1200","source_relpath":"AN2 wild additions/IMG_6004.jpg","drive_view":"https://drive.google.com/file/d/18BgujAIi7bwre-YJSkPJLzracA1_6WEo/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Wild / field context","filename":"IMG_6005.jpg","caption":"AN2-F9 — wild field context, hymenophore close-up, alternate view","id":"1sUIA227ZpNdlccdSJl7ZpdvqLFkl8Xf8","original":"https://drive.google.com/thumbnail?id=1sUIA227ZpNdlccdSJl7ZpdvqLFkl8Xf8&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1sUIA227ZpNdlccdSJl7ZpdvqLFkl8Xf8&sz=w1200","source_relpath":"AN2 wild additions/IMG_6005.jpg","drive_view":"https://drive.google.com/file/d/1sUIA227ZpNdlccdSJl7ZpdvqLFkl8Xf8/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Wild / field context","filename":"IMG_6006.jpg","caption":"AN2-F9 — collected specimen on foil with accession label visible","id":"1dFmI4JkIenBkscAmlVMcbhzOqoPLaDF4","original":"https://drive.google.com/thumbnail?id=1dFmI4JkIenBkscAmlVMcbhzOqoPLaDF4&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1dFmI4JkIenBkscAmlVMcbhzOqoPLaDF4&sz=w1200","source_relpath":"AN2 wild additions/IMG_6006.jpg","drive_view":"https://drive.google.com/file/d/1dFmI4JkIenBkscAmlVMcbhzOqoPLaDF4/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Source macro / specimen","filename":"IMG_6007.jpg","caption":"AN2-F9 — macro view of tooth-like hymenophore","id":"1_HwbvUqKpxG1xDgw6gpYIx1BRgLbz0Jc","original":"https://drive.google.com/thumbnail?id=1_HwbvUqKpxG1xDgw6gpYIx1BRgLbz0Jc&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1_HwbvUqKpxG1xDgw6gpYIx1BRgLbz0Jc&sz=w1200","source_relpath":"AN2 wild additions/IMG_6007.jpg","drive_view":"https://drive.google.com/file/d/1_HwbvUqKpxG1xDgw6gpYIx1BRgLbz0Jc/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Source macro / specimen","filename":"IMG_6008.jpg","caption":"AN2-F9 — macro view of tooth-like hymenophore, alternate focus","id":"1uWkv5EN-rOdIoVqYxxKGr22VFRN4fFee","original":"https://drive.google.com/thumbnail?id=1uWkv5EN-rOdIoVqYxxKGr22VFRN4fFee&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1uWkv5EN-rOdIoVqYxxKGr22VFRN4fFee&sz=w1200","source_relpath":"AN2 wild additions/IMG_6008.jpg","drive_view":"https://drive.google.com/file/d/1uWkv5EN-rOdIoVqYxxKGr22VFRN4fFee/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Source macro / specimen","filename":"IMG_6009.jpg","caption":"AN2-F9 — collected specimen overview on foil with accession label","id":"1W3QtN-7f-yQvfRx2WEsEE9THAa0O6XT_","original":"https://drive.google.com/thumbnail?id=1W3QtN-7f-yQvfRx2WEsEE9THAa0O6XT_&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1W3QtN-7f-yQvfRx2WEsEE9THAa0O6XT_&sz=w1200","source_relpath":"AN2 wild additions/IMG_6009.jpg","drive_view":"https://drive.google.com/file/d/1W3QtN-7f-yQvfRx2WEsEE9THAa0O6XT_/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Wild / field context","filename":"IMG_6003.jpg","caption":"AN2-F9 — fruiting bodies at tree base / woody substrate","id":"1pqPNPPkCoEbRAEa2YY8EL5WysmIh6Trw","original":"https://drive.google.com/thumbnail?id=1pqPNPPkCoEbRAEa2YY8EL5WysmIh6Trw&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1pqPNPPkCoEbRAEa2YY8EL5WysmIh6Trw&sz=w1200","source_relpath":"AN2 wild additions/IMG_6003.jpg","drive_view":"https://drive.google.com/file/d/1pqPNPPkCoEbRAEa2YY8EL5WysmIh6Trw/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F9","category":"Wild / field context","filename":"IMG_6001.jpg","caption":"AN2-F9 — wild collection context with accession label visible","id":"1cVPzzhOCDLwgBh_SzhLpb_V5worZpKeH","original":"https://drive.google.com/thumbnail?id=1cVPzzhOCDLwgBh_SzhLpb_V5worZpKeH&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1cVPzzhOCDLwgBh_SzhLpb_V5worZpKeH&sz=w1200","source_relpath":"AN2 wild additions/IMG_6001.jpg","drive_view":"https://drive.google.com/file/d/1cVPzzhOCDLwgBh_SzhLpb_V5worZpKeH/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F34","category":"Wild / field context","filename":"IMG_6152.jpg","caption":"AN2-F34 — Rutgers Jockey Hollow field-returned wild specimen, pore surface / hymenophore view","id":"13FQZ4rPGlZedyiQ88zYmm5xUcGgOvFEr","original":"https://drive.google.com/thumbnail?id=13FQZ4rPGlZedyiQ88zYmm5xUcGgOvFEr&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=13FQZ4rPGlZedyiQ88zYmm5xUcGgOvFEr&sz=w1200","source_relpath":"AN2 wild additions/IMG_6152.jpg","drive_view":"https://drive.google.com/file/d/13FQZ4rPGlZedyiQ88zYmm5xUcGgOvFEr/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F34","category":"Wild / field context","filename":"IMG_6153.jpg","caption":"AN2-F34 — Rutgers Jockey Hollow field-returned wild specimen, side profile with stipe and pore surface","id":"1V__CLZ2FVR_6oHJlQMa6VIRWU9c2NqTw","original":"https://drive.google.com/thumbnail?id=1V__CLZ2FVR_6oHJlQMa6VIRWU9c2NqTw&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1V__CLZ2FVR_6oHJlQMa6VIRWU9c2NqTw&sz=w1200","source_relpath":"AN2 wild additions/IMG_6153.jpg","drive_view":"https://drive.google.com/file/d/1V__CLZ2FVR_6oHJlQMa6VIRWU9c2NqTw/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F34","category":"Wild / field context","filename":"IMG_6154.jpg","caption":"AN2-F34 — Rutgers Jockey Hollow field-returned wild specimen, cap surface view","id":"1O9DkJTauERBEgqwFN6SCulq-jpcuh8Fm","original":"https://drive.google.com/thumbnail?id=1O9DkJTauERBEgqwFN6SCulq-jpcuh8Fm&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1O9DkJTauERBEgqwFN6SCulq-jpcuh8Fm&sz=w1200","source_relpath":"AN2 wild additions/IMG_6154.jpg","drive_view":"https://drive.google.com/file/d/1O9DkJTauERBEgqwFN6SCulq-jpcuh8Fm/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Wild / field context","filename":"IMG_6121.jpg","caption":"AN2-F25 — in-situ wild field view at Jockey Hollow, purple fruiting body with gills and stipe visible","id":"16beYprEoK2yN8boQNmG4hh7qWLIqsQXU","original":"https://drive.google.com/thumbnail?id=16beYprEoK2yN8boQNmG4hh7qWLIqsQXU&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=16beYprEoK2yN8boQNmG4hh7qWLIqsQXU&sz=w1200","source_relpath":"AN2 wild additions/IMG_6121.jpg","drive_view":"https://drive.google.com/file/d/16beYprEoK2yN8boQNmG4hh7qWLIqsQXU/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Wild / field context","filename":"IMG_6123.jpg","caption":"AN2-F25 — in-situ wild field view at Jockey Hollow, alternate angle showing gills, stipe, and leaf-litter substrate","id":"1xDLMzJF-lLWamkGilypbADxbuZjTBW_u","original":"https://drive.google.com/thumbnail?id=1xDLMzJF-lLWamkGilypbADxbuZjTBW_u&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1xDLMzJF-lLWamkGilypbADxbuZjTBW_u&sz=w1200","source_relpath":"AN2 wild additions/IMG_6123.jpg","drive_view":"https://drive.google.com/file/d/1xDLMzJF-lLWamkGilypbADxbuZjTBW_u/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Source macro / specimen","filename":"IMG_6124.jpg","caption":"AN2-F25 — collected specimen documentation with AN2 25 accession label visible","id":"11mv8Gd6WSYIq2xgPHiDd9_kzhitg64fc","original":"https://drive.google.com/thumbnail?id=11mv8Gd6WSYIq2xgPHiDd9_kzhitg64fc&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=11mv8Gd6WSYIq2xgPHiDd9_kzhitg64fc&sz=w1200","source_relpath":"AN2 wild additions/IMG_6124.jpg","drive_view":"https://drive.google.com/file/d/11mv8Gd6WSYIq2xgPHiDd9_kzhitg64fc/view"},
  {"folder":"AN2 wild additions","collection":"AN2","family":"AN","specimen":"AN2-F25","category":"Source macro / specimen","filename":"IMG_6125.jpg","caption":"AN2-F25 — collected specimen macro view showing cap and stipe morphology","id":"1oUCN_wtWLri1Jah_hDgv-a4ZJOnM2j00","original":"https://drive.google.com/thumbnail?id=1oUCN_wtWLri1Jah_hDgv-a4ZJOnM2j00&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1oUCN_wtWLri1Jah_hDgv-a4ZJOnM2j00&sz=w1200","source_relpath":"AN2 wild additions/IMG_6125.jpg","drive_view":"https://drive.google.com/file/d/1oUCN_wtWLri1Jah_hDgv-a4ZJOnM2j00/view"}
);


// AN2-F7 microscopy series — verified Google Drive upload, 2026-10-01.
// Explicit accession filenames; no visual-similarity assignment.
window.DRIVE_PHOTOS = window.DRIVE_PHOTOS || [];
window.DRIVE_PHOTOS.push(
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (1).png","caption":"AN2-F7 — annotated calibrated spore-mount field; nine fully legible measurements used in the validated dataset","id":"1fTOu4VmnIxtmGmA_LAphcmp3E50fQxMl","original":"https://drive.google.com/thumbnail?id=1fTOu4VmnIxtmGmA_LAphcmp3E50fQxMl&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1fTOu4VmnIxtmGmA_LAphcmp3E50fQxMl&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (1).png","drive_view":"https://drive.google.com/file/d/1fTOu4VmnIxtmGmA_LAphcmp3E50fQxMl/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (2).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"11OMyflPNisDvlfiKBu7IK2KR1uKl1jug","original":"https://drive.google.com/thumbnail?id=11OMyflPNisDvlfiKBu7IK2KR1uKl1jug&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=11OMyflPNisDvlfiKBu7IK2KR1uKl1jug&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (2).png","drive_view":"https://drive.google.com/file/d/11OMyflPNisDvlfiKBu7IK2KR1uKl1jug/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (3).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"1uEJTgt7_7IYxTBjxQK6f5G1fuQOwPrWJ","original":"https://drive.google.com/thumbnail?id=1uEJTgt7_7IYxTBjxQK6f5G1fuQOwPrWJ&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1uEJTgt7_7IYxTBjxQK6f5G1fuQOwPrWJ&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (3).png","drive_view":"https://drive.google.com/file/d/1uEJTgt7_7IYxTBjxQK6f5G1fuQOwPrWJ/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (4).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"1R268pfZVeE7u6fW_yQcIrfOuAIvMVtj3","original":"https://drive.google.com/thumbnail?id=1R268pfZVeE7u6fW_yQcIrfOuAIvMVtj3&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1R268pfZVeE7u6fW_yQcIrfOuAIvMVtj3&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (4).png","drive_view":"https://drive.google.com/file/d/1R268pfZVeE7u6fW_yQcIrfOuAIvMVtj3/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (5).png","caption":"AN2-F7 — annotated calibrated spore-mount field; sixteen fully legible measurements used in the validated dataset","id":"1ivmbvrNPSv9VoW_FVNWnpwVJZYiqIlh2","original":"https://drive.google.com/thumbnail?id=1ivmbvrNPSv9VoW_FVNWnpwVJZYiqIlh2&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1ivmbvrNPSv9VoW_FVNWnpwVJZYiqIlh2&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (5).png","drive_view":"https://drive.google.com/file/d/1ivmbvrNPSv9VoW_FVNWnpwVJZYiqIlh2/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (6).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"1yf73PCHSh1EXQW2jF_jKLEPaGVeIfRI9","original":"https://drive.google.com/thumbnail?id=1yf73PCHSh1EXQW2jF_jKLEPaGVeIfRI9&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1yf73PCHSh1EXQW2jF_jKLEPaGVeIfRI9&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (6).png","drive_view":"https://drive.google.com/file/d/1yf73PCHSh1EXQW2jF_jKLEPaGVeIfRI9/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (7).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"1CijRzF7SshFSEMbEGjAHzXEC1zq1zvRM","original":"https://drive.google.com/thumbnail?id=1CijRzF7SshFSEMbEGjAHzXEC1zq1zvRM&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1CijRzF7SshFSEMbEGjAHzXEC1zq1zvRM&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (7).png","drive_view":"https://drive.google.com/file/d/1CijRzF7SshFSEMbEGjAHzXEC1zq1zvRM/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (8).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"1BzQxWBbjXwXwMCJe3uYHXM9rL_XAu5UI","original":"https://drive.google.com/thumbnail?id=1BzQxWBbjXwXwMCJe3uYHXM9rL_XAu5UI&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1BzQxWBbjXwXwMCJe3uYHXM9rL_XAu5UI&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (8).png","drive_view":"https://drive.google.com/file/d/1BzQxWBbjXwXwMCJe3uYHXM9rL_XAu5UI/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (9).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"1mrZlNr-W9Fz4T8ynKDtRTMBaSVmxDco7","original":"https://drive.google.com/thumbnail?id=1mrZlNr-W9Fz4T8ynKDtRTMBaSVmxDco7&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1mrZlNr-W9Fz4T8ynKDtRTMBaSVmxDco7&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (9).png","drive_view":"https://drive.google.com/file/d/1mrZlNr-W9Fz4T8ynKDtRTMBaSVmxDco7/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (10).png","caption":"AN2-F7 — annotated calibrated spore-mount field; eighteen fully legible measurements used in the validated dataset","id":"1uscV3uJAPj1oPEwNamajV9ZvEzJ6p0hw","original":"https://drive.google.com/thumbnail?id=1uscV3uJAPj1oPEwNamajV9ZvEzJ6p0hw&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1uscV3uJAPj1oPEwNamajV9ZvEzJ6p0hw&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (10).png","drive_view":"https://drive.google.com/file/d/1uscV3uJAPj1oPEwNamajV9ZvEzJ6p0hw/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Microscopy","filename":"AN2-F7 SPM (11).png","caption":"AN2-F7 — microscopy field showing abundant repeated rounded to broadly ellipsoid spores","id":"1Y21EhbdJumQZiB8sdUJAZPBh2ZR_-aCt","original":"https://drive.google.com/thumbnail?id=1Y21EhbdJumQZiB8sdUJAZPBh2ZR_-aCt&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Y21EhbdJumQZiB8sdUJAZPBh2ZR_-aCt&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 SPM (11).png","drive_view":"https://drive.google.com/file/d/1Y21EhbdJumQZiB8sdUJAZPBh2ZR_-aCt/view"}
);


// AN2-F7 macro preparation / spore-print workflow images — user-supplied 2026-10-01.
window.DRIVE_PHOTOS = window.DRIVE_PHOTOS || [];
window.DRIVE_PHOTOS.push(
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Spore print / preparation","filename":"AN2-F7 prep macro 1.jpg","caption":"AN2-F7 — close preparation view showing foil, pale powdery deposit, and accession-linked slide edge","id":"1CxtKblkOPYLYFJBz1k3ZExntHrgBH08l","original":"https://drive.google.com/thumbnail?id=1CxtKblkOPYLYFJBz1k3ZExntHrgBH08l&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1CxtKblkOPYLYFJBz1k3ZExntHrgBH08l&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 prep macro 1.jpg","drive_view":"https://drive.google.com/file/d/1CxtKblkOPYLYFJBz1k3ZExntHrgBH08l/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Spore print / preparation","filename":"AN2-F7 prep macro 2.jpg","caption":"AN2-F7 — preparation overview with foil deposit and handwritten AN2 F7 slide label visible","id":"1586vw71M1jjNw7QNtjMOtyb7LaDyxv4E","original":"https://drive.google.com/thumbnail?id=1586vw71M1jjNw7QNtjMOtyb7LaDyxv4E&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1586vw71M1jjNw7QNtjMOtyb7LaDyxv4E&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 prep macro 2.jpg","drive_view":"https://drive.google.com/file/d/1586vw71M1jjNw7QNtjMOtyb7LaDyxv4E/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Spore print / preparation","filename":"AN2-F7 prep macro 3.jpg","caption":"AN2-F7 — alternate preparation overview of the same accession-linked foil and labeled slide setup","id":"15O7pJ2z2YECVfLbiI3-f8I6b55b9q3OF","original":"https://drive.google.com/thumbnail?id=15O7pJ2z2YECVfLbiI3-f8I6b55b9q3OF&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=15O7pJ2z2YECVfLbiI3-f8I6b55b9q3OF&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 prep macro 3.jpg","drive_view":"https://drive.google.com/file/d/15O7pJ2z2YECVfLbiI3-f8I6b55b9q3OF/view"},
  {"folder":"Jockey_Hollow_Atlas/AN2-F7","collection":"AN2","family":"AN","specimen":"AN2-F7","category":"Spore print / preparation","filename":"AN2-F7 prep microscope stage.jpg","caption":"AN2-F7 — accession-labeled preparation slide positioned on microscope stage during the microscopy workflow","id":"1MtYLXhv184Ab0pek4q3vOkmtnz4mvVFa","original":"https://drive.google.com/thumbnail?id=1MtYLXhv184Ab0pek4q3vOkmtnz4mvVFa&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1MtYLXhv184Ab0pek4q3vOkmtnz4mvVFa&sz=w1200","source_relpath":"Jockey_Hollow_Atlas/AN2-F7/AN2-F7 prep microscope stage.jpg","drive_view":"https://drive.google.com/file/d/1MtYLXhv184Ab0pek4q3vOkmtnz4mvVFa/view"}
);

window.DRIVE_PHOTOS = window.DRIVE_PHOTOS || [];
window.DRIVE_PHOTOS.push(
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (1).png","caption":"AN2-F41 — microscopy field view 1","id":"1oPlxdTLEu5BGUbs0LsOQOl60C4VWxU3h","original":"https://drive.google.com/thumbnail?id=1oPlxdTLEu5BGUbs0LsOQOl60C4VWxU3h&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1oPlxdTLEu5BGUbs0LsOQOl60C4VWxU3h&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (1).png","drive_view":"https://drive.google.com/file/d/1oPlxdTLEu5BGUbs0LsOQOl60C4VWxU3h/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (2).png","caption":"AN2-F41 — microscopy field view 2","id":"1PTaVSkdReky3Rzi2g3qPN2lhVENvK3Fz","original":"https://drive.google.com/thumbnail?id=1PTaVSkdReky3Rzi2g3qPN2lhVENvK3Fz&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1PTaVSkdReky3Rzi2g3qPN2lhVENvK3Fz&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (2).png","drive_view":"https://drive.google.com/file/d/1PTaVSkdReky3Rzi2g3qPN2lhVENvK3Fz/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (3).png","caption":"AN2-F41 — microscopy field view 3","id":"1B-PmsMLBbsgzB17h_Ki2Tn4_ZXp35Cmg","original":"https://drive.google.com/thumbnail?id=1B-PmsMLBbsgzB17h_Ki2Tn4_ZXp35Cmg&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1B-PmsMLBbsgzB17h_Ki2Tn4_ZXp35Cmg&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (3).png","drive_view":"https://drive.google.com/file/d/1B-PmsMLBbsgzB17h_Ki2Tn4_ZXp35Cmg/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (4).png","caption":"AN2-F41 — microscopy field view 4","id":"1Y-5tTy7p4MtM3rEzVAu_MFqeLQDWY7Up","original":"https://drive.google.com/thumbnail?id=1Y-5tTy7p4MtM3rEzVAu_MFqeLQDWY7Up&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Y-5tTy7p4MtM3rEzVAu_MFqeLQDWY7Up&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (4).png","drive_view":"https://drive.google.com/file/d/1Y-5tTy7p4MtM3rEzVAu_MFqeLQDWY7Up/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (5).png","caption":"AN2-F41 — calibrated measurement field 1","id":"12VoJOTUHCtXCudJjV4crvflL4YMOiG4H","original":"https://drive.google.com/thumbnail?id=12VoJOTUHCtXCudJjV4crvflL4YMOiG4H&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=12VoJOTUHCtXCudJjV4crvflL4YMOiG4H&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (5).png","drive_view":"https://drive.google.com/file/d/12VoJOTUHCtXCudJjV4crvflL4YMOiG4H/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (6).png","caption":"AN2-F41 — calibrated measurement field 2","id":"1DHoyYwW3I6z1LDY8J08ahHoHyEVBEtsq","original":"https://drive.google.com/thumbnail?id=1DHoyYwW3I6z1LDY8J08ahHoHyEVBEtsq&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1DHoyYwW3I6z1LDY8J08ahHoHyEVBEtsq&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (6).png","drive_view":"https://drive.google.com/file/d/1DHoyYwW3I6z1LDY8J08ahHoHyEVBEtsq/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (7).png","caption":"AN2-F41 — calibrated measurement field 3","id":"1GHI1hwtn0GdDn3mzF6buGBfG1ODxIdRz","original":"https://drive.google.com/thumbnail?id=1GHI1hwtn0GdDn3mzF6buGBfG1ODxIdRz&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1GHI1hwtn0GdDn3mzF6buGBfG1ODxIdRz&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (7).png","drive_view":"https://drive.google.com/file/d/1GHI1hwtn0GdDn3mzF6buGBfG1ODxIdRz/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (8).png","caption":"AN2-F41 — microscopy field view 8","id":"1TybLPrQLZQDOqnxKuAVcLxKyC8znCLun","original":"https://drive.google.com/thumbnail?id=1TybLPrQLZQDOqnxKuAVcLxKyC8znCLun&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1TybLPrQLZQDOqnxKuAVcLxKyC8znCLun&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (8).png","drive_view":"https://drive.google.com/file/d/1TybLPrQLZQDOqnxKuAVcLxKyC8znCLun/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (9).png","caption":"AN2-F41 — microscopy field view 9","id":"1twljQIOpldvNkQaKw5kbx8CrKPL70ia6","original":"https://drive.google.com/thumbnail?id=1twljQIOpldvNkQaKw5kbx8CrKPL70ia6&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1twljQIOpldvNkQaKw5kbx8CrKPL70ia6&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (9).png","drive_view":"https://drive.google.com/file/d/1twljQIOpldvNkQaKw5kbx8CrKPL70ia6/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (10).png","caption":"AN2-F41 — microscopy field view 10","id":"1pgW9UBj6Yj7jEUsXL5vM2IZ63NUjSBMy","original":"https://drive.google.com/thumbnail?id=1pgW9UBj6Yj7jEUsXL5vM2IZ63NUjSBMy&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1pgW9UBj6Yj7jEUsXL5vM2IZ63NUjSBMy&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (10).png","drive_view":"https://drive.google.com/file/d/1pgW9UBj6Yj7jEUsXL5vM2IZ63NUjSBMy/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (11).png","caption":"AN2-F41 — microscopy field view 11","id":"1DPZrZyP5BPp6YW3169qJ06DfGDl-nIHS","original":"https://drive.google.com/thumbnail?id=1DPZrZyP5BPp6YW3169qJ06DfGDl-nIHS&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1DPZrZyP5BPp6YW3169qJ06DfGDl-nIHS&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (11).png","drive_view":"https://drive.google.com/file/d/1DPZrZyP5BPp6YW3169qJ06DfGDl-nIHS/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (12).png","caption":"AN2-F41 — microscopy field view 12","id":"1TdQ9PDtpoiiGS8CDPWs0d9IywdCDDs6h","original":"https://drive.google.com/thumbnail?id=1TdQ9PDtpoiiGS8CDPWs0d9IywdCDDs6h&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1TdQ9PDtpoiiGS8CDPWs0d9IywdCDDs6h&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (12).png","drive_view":"https://drive.google.com/file/d/1TdQ9PDtpoiiGS8CDPWs0d9IywdCDDs6h/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Microscopy","filename":"AN2-F41 SPM (13).png","caption":"AN2-F41 — microscopy field view 13","id":"1uulITKB-5WfVJbzS_fqA3Yyl48eKj9Nl","original":"https://drive.google.com/thumbnail?id=1uulITKB-5WfVJbzS_fqA3Yyl48eKj9Nl&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1uulITKB-5WfVJbzS_fqA3Yyl48eKj9Nl&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 SPM (13).png","drive_view":"https://drive.google.com/file/d/1uulITKB-5WfVJbzS_fqA3Yyl48eKj9Nl/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Spore print / preparation","filename":"AN2-F41 prep macro (1).jpg","caption":"AN2-F41 — preparation/spore-print overview with labeled slide","id":"1Y86bChNMC9dp13u1UdLqkrsaNCOEU7Vl","original":"https://drive.google.com/thumbnail?id=1Y86bChNMC9dp13u1UdLqkrsaNCOEU7Vl&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Y86bChNMC9dp13u1UdLqkrsaNCOEU7Vl&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 prep macro (1).jpg","drive_view":"https://drive.google.com/file/d/1Y86bChNMC9dp13u1UdLqkrsaNCOEU7Vl/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Spore print / preparation","filename":"AN2-F41 prep macro (2).jpg","caption":"AN2-F41 — preparation/spore-print overview, view 2","id":"1Blb5Sq6Ps-gpP0ijU3mY8tyuYHauonKm","original":"https://drive.google.com/thumbnail?id=1Blb5Sq6Ps-gpP0ijU3mY8tyuYHauonKm&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1Blb5Sq6Ps-gpP0ijU3mY8tyuYHauonKm&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 prep macro (2).jpg","drive_view":"https://drive.google.com/file/d/1Blb5Sq6Ps-gpP0ijU3mY8tyuYHauonKm/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Spore print / preparation","filename":"AN2-F41 prep macro (3).jpg","caption":"AN2-F41 — preparation/spore-print detail, view 3","id":"15p97lTxLY6DqPYOWqms-DbnPl8jI4O1p","original":"https://drive.google.com/thumbnail?id=15p97lTxLY6DqPYOWqms-DbnPl8jI4O1p&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=15p97lTxLY6DqPYOWqms-DbnPl8jI4O1p&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 prep macro (3).jpg","drive_view":"https://drive.google.com/file/d/15p97lTxLY6DqPYOWqms-DbnPl8jI4O1p/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Spore print / preparation","filename":"AN2-F41 prep macro (4).jpg","caption":"AN2-F41 — preparation/spore-print overview, view 4","id":"10qXZx0AJ2HPVRYqNgNIxP6AyDGFFl63Q","original":"https://drive.google.com/thumbnail?id=10qXZx0AJ2HPVRYqNgNIxP6AyDGFFl63Q&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=10qXZx0AJ2HPVRYqNgNIxP6AyDGFFl63Q&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 prep macro (4).jpg","drive_view":"https://drive.google.com/file/d/10qXZx0AJ2HPVRYqNgNIxP6AyDGFFl63Q/view"}
);

window.DRIVE_PHOTOS = window.DRIVE_PHOTOS || [];
window.DRIVE_PHOTOS.push(
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Wild / field context","filename":"AN2-F41 field (1).jpg","caption":"AN2-F41 — in-situ field view showing intact red pileus and pore-bearing underside","id":"1pb3Xk0HjY2Qx3dMgjFwxQhIPWuIZZ7Zw","original":"https://drive.google.com/thumbnail?id=1pb3Xk0HjY2Qx3dMgjFwxQhIPWuIZZ7Zw&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1pb3Xk0HjY2Qx3dMgjFwxQhIPWuIZZ7Zw&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 field (1).jpg","drive_view":"https://drive.google.com/file/d/1pb3Xk0HjY2Qx3dMgjFwxQhIPWuIZZ7Zw/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Wild / field context","filename":"AN2-F41 field (2).jpg","caption":"AN2-F41 — dorsal field view of red pileus in leaf litter","id":"13-Y4UI4np9udZisYn0DvngieqkePeHOX","original":"https://drive.google.com/thumbnail?id=13-Y4UI4np9udZisYn0DvngieqkePeHOX&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=13-Y4UI4np9udZisYn0DvngieqkePeHOX&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 field (2).jpg","drive_view":"https://drive.google.com/file/d/13-Y4UI4np9udZisYn0DvngieqkePeHOX/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Wild / field context","filename":"AN2-F41 field (3).jpg","caption":"AN2-F41 — field specimen on foil with hymenophore, stipe/base, and AN2-F41 accession label visible","id":"1cKl4dFs-DYgyjQfEiqoRuxzfz_9KVbvi","original":"https://drive.google.com/thumbnail?id=1cKl4dFs-DYgyjQfEiqoRuxzfz_9KVbvi&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1cKl4dFs-DYgyjQfEiqoRuxzfz_9KVbvi&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 field (3).jpg","drive_view":"https://drive.google.com/file/d/1cKl4dFs-DYgyjQfEiqoRuxzfz_9KVbvi/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Wild / field context","filename":"AN2-F41 field (4).jpg","caption":"AN2-F41 — close field handling view emphasizing pore surface and stipe/base","id":"1pW7jJUXvA-rOfm0UHY4vYkgi65x3xMnl","original":"https://drive.google.com/thumbnail?id=1pW7jJUXvA-rOfm0UHY4vYkgi65x3xMnl&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=1pW7jJUXvA-rOfm0UHY4vYkgi65x3xMnl&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 field (4).jpg","drive_view":"https://drive.google.com/file/d/1pW7jJUXvA-rOfm0UHY4vYkgi65x3xMnl/view"},
  {"folder":"AN2 lab additions","collection":"AN2","family":"AN","specimen":"AN2-F41","category":"Wild / field context","filename":"AN2-F41 field (5).jpg","caption":"AN2-F41 — field specimen and accession label on foil, pileus and attached base visible","id":"16KP97mm-b1QA1I-r6xeT8f-FwKmpwzZ5","original":"https://drive.google.com/thumbnail?id=16KP97mm-b1QA1I-r6xeT8f-FwKmpwzZ5&sz=w2400","thumb":"https://drive.google.com/thumbnail?id=16KP97mm-b1QA1I-r6xeT8f-FwKmpwzZ5&sz=w1200","source_relpath":"AN2 lab additions/AN2-F41 field (5).jpg","drive_view":"https://drive.google.com/file/d/16KP97mm-b1QA1I-r6xeT8f-FwKmpwzZ5/view"}
);

window.SPECIMEN_ENRICHMENTS = window.SPECIMEN_ENRICHMENTS || {};
window.SPECIMEN_ENRICHMENTS["AN2-F9"] = {
  status: "AN2-F9 complete dataset — Jockey Hollow wild context, field specimen morphology, laboratory preparation, microscopy, and measured spore imagery integrated.",
  sourceLine: "Rutgers/Jockey Hollow accession AN2-F9. The record combines wild and post-collection macromorphology, explicit accession labeling, laboratory preparation photographs, and seven microscopy fields. The macroscopic measurement master records a 13.2 cm fungal-body/pileus measurement and no visible stipe. Microscopic statistics use only fully legible on-image annotations; obscured values were excluded rather than reconstructed.",
  summary: {
    "Growth / Description": "Large, sessile to broadly laterally attached, shelf-like to confluent basidiomata arising from woody substrate at the base of a tree. Fruiting tissue forms overlapping, irregularly fan-shaped lobes rather than a centrally stipitate mushroom. The basidiomata are robust, tough-looking, and strongly differentiated into an upper pileus surface and a hydnoid fertile surface.",
    "Size": "Macroscopic measurement master: 13.2 cm for the fungal body/pileus; no visible stipe recorded. Microscopy: 37 fully legible on-image measurements across three measured fields, range 1.75–3.27 µm, mean 2.54 µm, median 2.59 µm.",
    "Color": "Upper surface warm reddish brown to orange-brown and chestnut, variably darker toward older central tissue, with a sharply paler cream to buff-white actively growing margin. Hymenophore tan, gray-brown to buff-brown; exposed context pale cream to whitish where visible.",
    "Cap / Pileus": "Pileus broad, irregular, fan-shaped to semicircular and frequently confluent with adjacent lobes; surface dry to matte, uneven and locally zonate, with reddish-brown to orange-brown pigmentation. Margin conspicuously paler, thickened, rounded to undulate, and cream-buff; lobes overlap and fuse into compound shelves.",
    "Hymenophore": "Hydnoid. Fertile undersurface densely covered with closely packed, pendent teeth or spines rather than pores or lamellae. Teeth are tapered, vertically oriented, and tan to gray-brown, producing a distinctly shaggy or odontioid lower surface. The hymenophore extends broadly across the underside of the shelves.",
    "Spores": "Microscopy fields show abundant small rounded to subglobose spore-like bodies, often occurring in clusters within the mount. Thirty-seven fully legible calibrated annotations in the measured fields span 1.75–3.27 µm (mean 2.54 µm; median 2.59 µm). These values are preserved as the observed on-image measurement set.",
    "Stem / Stipe": "No differentiated central stipe is present in the documented basidiomata; the specimen is sessile to laterally attached. The measurement master likewise records no visible stipe.",
    "Veil": "No partial veil, annulus, cortina, or universal-veil remnant is visible or morphologically expected from the documented sessile shelf-like basidiome architecture. This is an observation of the supplied material, not a taxonomic inference.",
    "Volva / Universal veil": "No volva or saccate basal structure is visible in the supplied wild or collected material.",
    "Base / Substrate": "Basidiomata arise directly from woody substrate at the base of a standing tree or associated decayed wood. Attachment is broad and lateral to resupinate-reflexed in portions; leaf litter surrounds the fruiting site.",
    "Context / Flesh": "Context appears pale cream to whitish, thick and firm where broken or exposed, contrasting with the darker upper surface and toothed hymenophore. Texture cannot be physically tested from the photographic record.",
    "Bruising / Staining": "No reproducible bruising reaction was intentionally documented. Darker reddish-brown areas may reflect age, moisture, handling, or natural pigmentation and are not interpreted as a chemical staining reaction.",
    "Odor": "Not recorded in the current specimen workflow.",
    "Taste": "Not tested / not recorded.",
    "Chemical reactions": "Not performed or not recorded.",
    "Microscopy record": "Seven AN2-F9 microscopy frames are accession-linked by filename. Three measured fields contain 37 fully legible annotations used for the quantitative summary; one partially obscured annotation was excluded. No hidden or truncated value was inferred.",
    "Spore print / preparation": "Two labeled AN2-F9 foil/slide preparation photographs document the laboratory preparation and preserve accession continuity between the macroscopic specimen and microscopy series.",
    "Record type": "Curated full-data specimen record",
    "Identification status": "Unresolved in the atlas; morphology is documented without forcing a species-level identification.",
    "Assignment rule": "Explicit AN2-F9 accession labels and filenames; no visual-similarity reassignment."
  },
  completeness: [
    ["Photo provenance","Yes"],
    ["Explicit specimen accession","Yes"],
    ["Wild / field imagery","Yes"],
    ["Embedded/source imagery","Yes"],
    ["Spore-print / preparation imagery","Yes"],
    ["Microscopy imagery","Yes"],
    ["Measurements","Yes"],
    ["Macroscopic measurement","Yes — 13.2 cm; no visible stipe"],
    ["Morphology fields reviewed","Yes"],
    ["Wild + laboratory pairing","Yes"],
    ["Identified","No — taxonomic identification unresolved"]
  ]
};

window.SPECIMEN_ENRICHMENTS["AN2-F34"] = {
  status: "AN2-F34 complete dataset — Rutgers Jockey Hollow field-returned wild specimen, macromorphology, spore-print preparation, microscopy, and annotated spore measurements integrated.",
  sourceLine: "Rutgers team wild collection from Jockey Hollow. The three wild-source photographs document the specimen after field return rather than in situ at the exact collection point; the visible foil accession label reads AN2 F34. Laboratory records include spore-print preparation imagery and five annotated microscopy fields. This distinction between wild provenance and absence of an in-situ photograph is retained explicitly.",
  summary: {
    "Growth / Description": "Robust, centrally to slightly eccentrically stipitate boletoid basidiome with a fleshy pileus and poroid hymenophore. The collected wild specimen is intact enough to document cap, pore surface, stipe, and basal condition, although the exact in-situ orientation and surrounding substrate were not photographed.",
    "Size": "No calibrated macroscopic ruler measurement is currently preserved for the field-returned AN2-F34 basidiome. Microscopy annotations document elongate to ellipsoid spores with visible long-axis measurements approximately 9.07–12.12 µm and short-axis measurements approximately 2.18–5.21 µm.",
    "Color": "Pileus ochre-brown to orange-brown and tawny, with paler cream to yellowish exposed or abraded areas. Pore surface yellow-brown to olive-brown, becoming darker with age or handling. Stipe pale cream to buff with tan-brown discoloration and adhering soil toward the base.",
    "Cap / Pileus": "Pileus broad, fleshy, convex to broadly convex, dry to matte, ochre-brown to orange-brown. Surface is irregularly cracked, abraded, or weathered in places, exposing paler cream-yellow context beneath; margin thick, rounded and entire to slightly uneven where handled.",
    "Hymenophore": "Poroid and tubular rather than lamellate. Undersurface densely covered with small to medium, irregularly angular to somewhat labyrinthine pores, yellow-brown to olive-brown. Tubes appear relatively deep and are clearly separable morphologically from the pileus context. No gills or teeth are present.",
    "Spores": "Five annotated microscopy fields document repeated elongate to narrowly ellipsoid brownish spores. Visible annotations include long-axis values approximately 9.07–12.12 µm and short-axis values approximately 2.18–5.21 µm. Mount medium and objective/magnification are not completely documented, so the atlas preserves these as observed on-image dimensions without species-level inference.",
    "Stem / Stipe": "Stipe stout, central to slightly eccentric, solid-appearing, pale cream to buff, broadly cylindrical to weakly clavate, with faint longitudinal texture and scattered brownish staining. The lower portion is incompletely preserved/obscured by collected debris, limiting detailed basal architecture.",
    "Veil": "No annulus or persistent partial-veil structure is visible in the supplied photographs.",
    "Volva / Universal veil": "No volva, saccate cup, or discrete universal-veil remnant is visible. The basal portion is not preserved sufficiently to exclude every developmental remnant, but no such structure is demonstrated.",
    "Base / Substrate": "Basal tissue is field-collected with adhering soil and organic debris. Exact in-situ substrate contact was not photographed; therefore terrestrial versus directly woody attachment is not asserted beyond the Rutgers wild-collection provenance.",
    "Context / Flesh": "Exposed pileus and stipe context appear pale cream to yellowish-white, thick and fleshy. No latex, hollow chambers, or rapid color change on sectioning were recorded.",
    "Bruising / Staining": "Brownish discoloration is present on the pore surface and stipe, but no standardized pressure-bruising test or time-course color reaction was documented; these color changes are therefore recorded descriptively rather than interpreted diagnostically.",
    "Odor": "Not recorded in the current specimen workflow.",
    "Taste": "Not tested / not recorded.",
    "Chemical reactions": "Not performed or not recorded.",
    "Microscopy record": "Five accession-linked microscopy images (AN2-F34 SPMV1–SPMV5) contain multiple on-image spore measurements. The repeated measured morphology is elongate to ellipsoid, with visible long- and short-axis annotations retained exactly as documentary evidence.",
    "Spore print / preparation": "AN2-F34 spore-print and preparation imagery documents a broad, patchy radial deposit, pale tan to light brown and uneven in density, with accession continuity into the measured microscopy series.",
    "Record type": "Curated full-data specimen record",
    "Wild-image type": "Field-returned wild specimen documentation; no in-situ ground photograph",
    "Identification status": "Unresolved in the atlas; boletoid morphology is documented without assigning genus or species.",
    "Assignment rule": "Visible AN2 F34 accession label and accession-linked microscopy filenames; no visual-similarity reassignment."
  },
  completeness: [
    ["Photo provenance","Yes"],
    ["Explicit specimen accession","Yes"],
    ["Wild / field imagery","Yes — field-returned specimen"],
    ["In-situ habitat photograph","No — not available"],
    ["Embedded/source imagery","Yes"],
    ["Spore-print imagery","Yes"],
    ["Microscopy imagery","Yes"],
    ["Measurements","Yes — annotated microscopic measurements"],
    ["Macroscopic calibrated measurements","Not available"],
    ["Morphology fields reviewed","Yes"],
    ["Wild + laboratory pairing","Yes"],
    ["Identified","No — taxonomic identification unresolved"]
  ]
};

window.SPECIMEN_ENRICHMENTS["AN2-F25"] = {
  status: "AN2-F25 complete dataset — in-situ Jockey Hollow field documentation, collected-specimen morphology, spore-print preparation, microscopy, and annotated spore measurements integrated.",
  sourceLine: "Rutgers Jockey Hollow specimen AN2-F25. Provenance is supported by two in-situ field photographs, four verified laboratory specimen views, two post-collection specimen photographs including a visible AN2 25 accession label, two spore-print/preparation photographs, and seven microscopy frames. Descriptions are restricted to characters visible in the supplied record; unavailable calibrated macroscopic dimensions are explicitly reported rather than inferred.",
  summary: {
    "Growth / Description": "Terrestrial, centrally stipitate, fleshy agaricoid basidiomata documented in situ among deciduous leaf litter at Jockey Hollow. At least two fruiting bodies occur together. Habit is robust and lamellate, with strongly violet-purple pigmentation extending across pileus, lamellae, and stipe.",
    "Size": "No calibrated macroscopic ruler measurement is currently preserved for AN2-F25; unsupported centimeter dimensions are therefore not assigned. Annotated microscopic measurements visible across the supplied measured fields span approximately 3.25–8.31 µm.",
    "Color": "Pileus deep violet to purple, locally dark plum-violet; lamellae violet to muted lilac-brown; stipe pale lilac to violet, becoming paler to whitish toward the enlarged base. Brown soil and forest debris adhere to basal tissue. Spore deposit light to medium cinnamon-brown.",
    "Cap / Pileus": "Pileus convex to broadly convex, fleshy and comparatively thick, deep violet-purple, dry to matte and smooth to very finely fibrillose. Margin entire to slightly undulate and distinctly incurved in the younger-looking field view. A collected cap shows a localized tan-brown abraded or discolored patch, interpreted as surface damage rather than a diagnostic color reaction.",
    "Hymenophore": "Lamellate. True lamellae are clearly exposed in field and collected-specimen views; they are violet to lilac-brown, moderately close, with interlamellar spacing visible. Attachment is clearly to the stipe and non-decurrent; the available junction views do not justify a narrower adnate-versus-adnexed designation.",
    "Spores": "Spore-print deposit light to medium cinnamon-brown and uneven in density. Microscopy shows numerous rounded to broadly ellipsoid brownish spores. Annotated linear measurements occur in SPMV2, SPMV3, SPMV5, SPMV6, and SPMV7 and span approximately 3.25–8.31 µm. Because objective, mount medium, stain, and measurement-axis convention are incompletely documented, these are retained as observed image measurements rather than converted to a formal taxonomic range.",
    "Stem / Stipe": "Stipe central, stout, solid-appearing, longitudinally fibrillose, pale lilac to violet, approximately equal through much of its length but widening conspicuously toward the base. Surface shows localized brownish soil/handling staining. No persistent annulus is visible.",
    "Veil": "No persistent membranous annulus is visible. No cortina-like remnants can be demonstrated confidently from the supplied photographs; absence in these mature views does not establish absence at earlier developmental stages.",
    "Volva / Universal veil": "No saccate volva or other discrete universal-veil structure is visible. Basal enlargement is continuous with the stipe rather than appearing as a free cup.",
    "Base / Substrate": "Base distinctly enlarged, bulbose to clavate, pale whitish to lilac, with adhering soil and leaf debris. In-situ photographs show terrestrial emergence through deciduous leaf litter; no direct woody attachment is visible.",
    "Context / Flesh": "Exposed tissue appears pale to whitish and fleshy. Internal chambering, latex, color change after sectioning, and texture under pressure were not documented.",
    "Bruising / Staining": "No controlled bruising reaction was recorded. Brownish localized discoloration on stipe and cap is present but cannot be separated confidently from handling, soil contact, age, or abrasion.",
    "Odor": "Not recorded in the current specimen workflow.",
    "Taste": "Not tested / not recorded.",
    "Chemical reactions": "Not performed or not recorded.",
    "Microscopy record": "Seven microscopy frames are accession-linked explicitly to AN2-F25 (SPMV1–SPMV7). SPMV2, SPMV3, SPMV5, SPMV6, and SPMV7 contain annotated linear measurements; SPMV1 and SPMV4 are unannotated fields. Observed values span approximately 3.25–8.31 µm.",
    "Spore print / preparation": "Two AN2-F25 spore-print/preparation photographs document a light to medium cinnamon-brown deposit with uneven radial density and maintain accession continuity into microscopy.",
    "Record type": "Curated full-data specimen record",
    "Identification status": "Unresolved in the atlas; morphology is documented without forcing a species-level identification.",
    "Assignment rule": "Explicit accession labeling and source filenames; no visual-similarity reassignment."
  },
  completeness: [
    ["Photo provenance","Yes"],
    ["Explicit specimen accession","Yes"],
    ["Wild / field imagery","Yes"],
    ["In-situ habitat photograph","Yes"],
    ["Embedded/source imagery","Yes"],
    ["Spore-print imagery","Yes"],
    ["Microscopy imagery","Yes"],
    ["Measurements","Yes — annotated microscopic measurements"],
    ["Macroscopic calibrated measurements","Not available"],
    ["Morphology fields reviewed","Yes"],
    ["Wild + laboratory pairing","Yes"],
    ["Identified","No — taxonomic identification unresolved"]
  ]
};


window.SPECIMEN_ENRICHMENTS["AN2-F38"] = {
  status: "AN2-F38 complete paired dataset — in-situ wild imagery, accession-linked specimen macro views, confirmed spore microscopy, and measurement record integrated.",
  sourceLine: "Rutgers/Jockey Hollow accession AN2-F38. The record pairs two user-supplied in-situ field photographs with five post-collection specimen photographs from the same submitted AN2-F38 series, including multiple frames with a visible handwritten AN2 F38 accession label. Existing microscopy fields are preserved and the imaged measured particles are confirmed here as spores. Their on-image measurements are attributed to AN2-F38 as a successful specimen-linked spore objective.",
  summary: {
    "Growth / Description": "Small, solitary agaricoid basidiome arising from deciduous leaf litter and shallow woodland duff. Field views show a bright orange, centrally stipitate fruit body emerging singly from the litter layer. Post-collection views confirm a slender pale stipe, pale lamellae, a distinct annulus, and basal universal-veil tissue.",
    "Size": "Macroscopic measurement master: cap diameter 2.9 cm; stipe top 0.1 cm, middle 0.1 cm, base 0.1 cm; stipe height 4.8 cm. Confirmed spore microscopy: 24 fully legible on-image measurements, range 1.06–6.13 µm, mean 2.39 µm, median 2.28 µm, sample SD 0.93 µm. The main measured spore population excluding the single 6.13 µm outlier spans 1.06–3.10 µm with mean 2.23 µm and median 2.17 µm (n=23). Two cropped V5 annotations are excluded from quantitative statistics because their complete values are not visible.",
    "Color": "Pileus vivid yellow-orange to orange, brighter centrally in some views and deeper orange toward the margin. Lamellae pale white to cream. Stipe white to ivory. Annulus and basal universal-veil tissue white to ivory.",
    "Cap / Pileus": "Pileus small, smooth, convex to hemispherical, nearly circular in dorsal view, with an even margin. Surface appears glabrous and slightly lustrous in the supplied photographs.",
    "Hymenophore": "Lamellate. Lamellae pale white to cream and appear free to narrowly separated from the stipe in the available views. Gill faces are thin, regular, and radially arranged.",
    "Spores": "Confirmed spores are present throughout the AN2-F38 microscopy series. Across the measured fields, 24 fully legible on-image spore measurements are preserved: 2.86, 2.41, 2.01, 2.39, 2.62, 2.14, 6.13, 2.06, 2.01, 2.47, 1.90, 2.84, 3.10, 2.70, 2.17, 1.06, 1.80, 2.74, 1.91, 1.54, 1.56, 2.06, 2.44, and 2.51 µm. Overall range 1.06–6.13 µm; mean 2.39 µm; median 2.28 µm; sample SD 0.93 µm; n=24. The dominant measured population is 1.06–3.10 µm; the single 6.13 µm spore is retained as a larger measured outlier rather than discarded. Two additional annotations in microscopy field V5 are cropped at the image edge and are excluded from calculations rather than reconstructed. Morphologically, the spores are predominantly small, rounded to subglobose, smooth-appearing, hyaline to weakly refractile in the transmitted-light images, and occur singly as well as in loose local clusters.",
    "Stem / Stipe": "Stipe central, slender, cylindrical, pale white to ivory, proportionally long relative to pileus width, with a distinct superior annulus and a narrow profile through most of its length.",
    "Veil": "A distinct partial-veil remnant is present as a small, delicate annulus on the upper stipe. The annulus is thin and membranous in the documented views.",
    "Volva / Universal veil": "Basal white universal-veil tissue is visible in the full post-collection specimen view. The basal structure is lobed to sheathing rather than a broad sac, and is recorded conservatively as universal-veil tissue / volval remnant present.",
    "Base / Substrate": "Observed terrestrially from deciduous leaf litter and woodland duff over soil. Field photographs document dry leaves, twigs, and forest-floor organic debris immediately surrounding the basidiome.",
    "Context / Flesh": "Internal flesh was not sectioned in the supplied set. Visible exposed tissue is white to pale cream. Texture and staining response cannot be confirmed from photographs alone.",
    "Bruising / Staining": "No reproducible bruising or staining reaction was intentionally documented in the current image set.",
    "Odor": "Not recorded.",
    "Taste": "Not tested / not recorded.",
    "Chemical reactions": "Not performed or not recorded.",
    "Microscopy record": "Six accession-linked AN2-F38 microscopy fields are preserved in the atlas. Four fields contain measurement annotations. V1 contributes six legible spore measurements (2.86, 2.41, 2.01, 2.39, 2.62, 2.14 µm; mean 2.41 µm). V3 contributes one measured spore at 6.13 µm. V4 contributes ten legible measurements (2.06, 2.01, 2.47, 1.90, 2.84, 3.10, 2.70, 2.17, 1.06, 1.80 µm; mean 2.21 µm). V5 contributes seven fully legible measurements (2.74, 1.91, 1.54, 1.56, 2.06, 2.44, 2.51 µm; mean 2.11 µm); two additional V5 labels are cropped at the image edge and are excluded. Combined validated statistics: n=24, range 1.06–6.13 µm, mean 2.39 µm, median 2.28 µm, sample SD 0.93 µm. The microscopy objective is recorded as successfully obtained and specimen-linked.",
    "Spore print / preparation": "Two AN2-F38 foil/slide preparation photographs are preserved. Both document the preparation workflow and accession continuity; at macro scale the visible deposit is faint to inconclusive, so the preparation images are retained as provenance rather than used alone to infer spore-print color.",
    "Record type": "Curated complete paired specimen record",
    "Identification status": "Taxonomic identification unresolved in the atlas; morphology is documented without forcing a species-level identification.",
    "Assignment rule": "Two field images were explicitly supplied by the user as AN2-F38 on 2026-10-01. Five post-collection images belong to the same submitted series; four visibly show the handwritten AN2 F38 accession label. No visual-similarity reassignment is used."
  },
  completeness: [
    ["Photo provenance","Yes"],
    ["Explicit specimen accession","Yes"],
    ["Wild / field imagery","Yes"],
    ["Embedded/source imagery","Yes"],
    ["Spore-print / preparation imagery","Yes — 2 preparation views"],
    ["Microscopy imagery","Yes"],
    ["Measurements","Yes"],
    ["Spore measurements","Yes"],
    ["Spore measurement count","24 fully legible annotations"],
    ["Spore measurement range","1.06–6.13 µm"],
    ["Spore mean / median","2.39 / 2.28 µm"],
    ["Spore sample SD","0.93 µm"],
    ["Confirmed spores documented","Yes"],
    ["Spore objective obtained","Yes"],
    ["Successful microscopic spore record","Yes"],
    ["Macroscopic measurement","Yes — cap 2.9 cm; stipe 0.1 / 0.1 / 0.1 cm; height 4.8 cm"],
    ["Morphology fields reviewed","Yes"],
    ["Wild + laboratory pairing","Yes"],
    ["Identified","No — taxonomic identification unresolved"]
  ]
};


window.SPECIMEN_ENRICHMENTS["AN2-F7"] = {
  status: "AN2-F7 complete dataset — Jockey Hollow wild context, verified laboratory specimen views, macroscopic measurements, and calibrated spore microscopy integrated.",
  sourceLine: "Rutgers/Jockey Hollow accession AN2-F7. The atlas preserves two wild-context photographs, three accession-linked specimen/laboratory views, the Rutgers macroscopic measurement record, and eleven AN2-F7 microscopy fields supplied and completed on 2026-10-01. The Motic BA310 / Moticam 2300 imaging system measurement calibration was reviewed with Motic technical support prior to quantitative acquisition. Quantitative spore statistics use the 43 fully legible annotations established from the submitted microscopy series; no unreadable or cropped value is inferred.",
  summary: {
    "Growth / Description": "Macroscopic wild and laboratory documentation is preserved under the AN2-F7 accession. The specimen is an agaricoid, lamellate fruit body with a clearly documented gilled hymenophore. The specimen is treated as a single provenance-linked record from field context through laboratory preparation and microscopy; morphology is documented descriptively without forcing a taxonomic identification.",
    "Hymenophore": "Lamellate. The underside is clearly gilled, with lamellae packed close to tight and locally crowded. Gill density is high across the documented hymenophore. This record preserves the observed gill spacing as close to tight/crowded; no narrower statement about exact stipe attachment is made here unless supported by a fully diagnostic junction view.",
    "Bruising / Staining": "Distinct darker brown bruising / discoloration is visible on the stipe against the otherwise cream-to-khaki stipe surface. The atlas records this as a real observed macroscopic character. Because no standardized pressure-bruising time course or chemical test is documented, the darker brown areas are not assigned a mechanistic cause beyond visible bruising/discoloration.",
    "Color": "Macroscopic coloration ranges from cream to khaki to brown across the documented specimen. The stipe is pale cream to khaki overall with distinct darker brown bruising / discoloration visible on the stipe surface. These darker brown areas are documented as observed bruising/discoloration rather than interpreted as a specific chemical reaction.",
    "Size": "Rutgers macroscopic measurement master: cap diameter 5.1 cm; stipe top diameter 1.9 cm, middle diameter 1.5 cm, base diameter 1.0 cm; stipe height was not stated and is not inferred. Confirmed microscopy dataset: n=43 fully legible spore measurements, range 2.28–5.22 µm, mean 3.91 µm, median 3.93 µm, sample SD 0.64 µm.",
    "Spores": "Across the submitted AN2-F7 microscopy series, spores are abundant and repeatedly observed across multiple fields. They are rounded to broadly ellipsoid / subglobose, smooth-appearing, hyaline to weakly refractile in transmitted light, fairly uniform in overall form, and occur in loose clusters as well as dense local concentrations. No obvious coarse ornamentation is visible at this imaging level. Forty-three fully legible calibrated measurements form the validated quantitative dataset: range 2.28–5.22 µm, mean 3.91 µm, median 3.93 µm, sample SD 0.64 µm.",
    "Microscopy record": "Eleven accession-linked AN2-F7 microscopy images are preserved (AN2-F7 SPM (1) through AN2-F7 SPM (11)). Three measured fields contribute the validated n=43 dataset: measured field 1 n=9, mean 3.82 µm; measured field 2 n=16, mean 3.96 µm; measured field 3 n=18, mean 3.92 µm. Combined statistics: n=43, range 2.28–5.22 µm, mean 3.91 µm, median 3.93 µm, sample SD 0.64 µm. The microscopy objective is recorded as successfully obtained.",
    "Calibration / instrumentation": "Motic BA310 / Moticam 2300 imaging system; measurement calibration reviewed with Motic technical support prior to quantitative acquisition.",
    "Spore print / preparation": "Four accession-linked AN2-F7 macro preparation photographs are preserved. They document foil with a visible pale white to off-white powdery deposit, a slide handwritten AN2 F7, and the labeled preparation slide positioned on the microscope stage. These images preserve continuity from macro preparation through microscopy. The deposit is described visually as pale/whitish; the photographs are retained primarily as preparation and accession-provenance evidence rather than used alone to make a stronger taxonomic spore-print color claim.",
    "Macroscopic measurements": "Cap diameter 5.1 cm; stipe top 1.9 cm; stipe middle 1.5 cm; stipe base 1.0 cm. Stipe height not stated in the source measurement record.",
    "Record type": "Curated full-data specimen record",
    "Identification status": "Taxonomic identification unresolved in the atlas; observed macro- and micromorphology are preserved without forcing genus or species.",
    "Assignment rule": "Explicit AN2-F7 accession filenames and existing accession-linked field/laboratory records only; no visual-similarity reassignment."
  },
  completeness: [
    ["Photo provenance","Yes"],
    ["Explicit specimen accession","Yes"],
    ["Wild / field imagery","Yes — 2 views"],
    ["Embedded/source imagery","Yes — 3 views"],
    ["Microscopy imagery","Yes — 11 views"],
    ["Measurements","Yes"],
    ["Macroscopic measurement","Yes — cap 5.1 cm; stipe 1.9 / 1.5 / 1.0 cm; height not stated"],
    ["Spore measurements","Yes"],
    ["Spore measurement count","43 fully legible annotations"],
    ["Spore measurement range","2.28–5.22 µm"],
    ["Spore mean / median","3.91 / 3.93 µm"],
    ["Spore sample SD","0.64 µm"],
    ["Measured microscopy fields","3 — n=9 / 16 / 18"],
    ["Calibration provenance","Yes — Motic BA310 / Moticam 2300; reviewed with Motic technical support"],
    ["Spore objective obtained","Yes"],
    ["Successful microscopic spore record","Yes"],
    ["Hymenophore documented","Yes — lamellate; close to tight / crowded gills"],
    ["Color documented","Yes — cream to khaki to brown"],
    ["Stipe bruising / discoloration","Yes — darker brown"],
    ["Morphology fields reviewed","Yes — macro and microscopy; unsupported characters are not inferred"],
    ["Wild + laboratory pairing","Yes"],
    ["Spore-print / preparation imagery","Yes — 4 accession-linked macro preparation views"],
    ["Identified","No — taxonomic identification unresolved"]
  ]
};

window.SPECIMEN_ENRICHMENTS["AN2-F5"] = {
  status: "AN2-F5 microscopy objective currently blocked — no AN2-F5 spore sample is presently available in the active laboratory material. The sample may exist elsewhere in the laboratory archive, but that has not been verified.",
  sourceLine: "Laboratory status update recorded 2026-10-01 from the user during active workshop/lab work. AN2-F5 macroscopic measurement data remain preserved, but no spore microscopy run should be represented as completed or failed because the required spore sample was not available for examination.",
  summary: {
    "Microscopy objective": "Not attempted in the current session because no verified AN2-F5 spore sample was available.",
    "Spore material status": "Not presently available in the active lab set; possible archived material is unverified.",
    "Record integrity note": "This is a material-availability limitation, not a negative microscopy result. No spore measurements or microscopic morphology are inferred."
  },
  completeness: [
    ["Microscopy objective attempted","No — verified AN2-F5 spore material unavailable"],
    ["Spore sample available","No — not present in active lab material; archive status unverified"],
    ["Microscopy result","Not applicable — objective not run"]
  ]
};

window.SPECIMEN_ENRICHMENTS["AN2-F31"] = {
  status: "AN2-F31 microscopy objective currently blocked — a verified AN2-F31 spore sample has not been located in the active laboratory material. Archived material may exist elsewhere, but that has not been verified.",
  sourceLine: "Laboratory status update recorded 2026-10-01 during active workshop/lab work. AN2-F31 retains its existing macro/specimen and spore-preparation documentation. No microscopy result is assigned because the required physical spore sample has not been confirmed as available for examination.",
  summary: {
    "Microscopy objective": "Not attempted in the current session because verified AN2-F31 spore material was not located.",
    "Spore material status": "Not presently located in the active lab set; possible archived material remains unverified.",
    "Record integrity note": "This is a material-availability limitation, not a microscopy failure. Existing macro and preparation records remain valid and preserved; no microscopic morphology or measurements are inferred."
  },
  completeness: [
    ["Microscopy objective attempted","No — verified AN2-F31 spore material not located"],
    ["Spore sample available","Unverified — not present in active lab material"],
    ["Microscopy result","Not applicable — objective not run"]
  ]
};

window.SPECIMEN_ENRICHMENTS["AN2-F41"] = {
  status: "AN2-F41 complete dataset — in-situ field context, verified macro specimen views, accession-linked spore-print/preparation documentation, and 13 microscopy fields including 3 calibrated measurement fields integrated.",
  sourceLine: "Rutgers/Jockey Hollow accession AN2-F41. Five accession-linked 2026-10-01 field photographs now document the intact specimen in leaf litter, pileus, pore-bearing hymenophore, stipe/base, and accession-labeled field handling. Existing verified laboratory specimen views AN2-F41.JPG and AN2-F41V2.JPG are retained. The original AN2-F41SP.JPG spore-print record is supplemented by four preparation photographs and thirteen accession-linked microscopy images. Quantitative values below are transcribed only from fully legible on-image Motic measurement annotations; cropped or unreadable labels are excluded.",
  summary: {
    "Growth / Description": "Accession continuity is now documented from in-situ field context through verified laboratory specimen views, visible spore deposit, labeled slide preparation, and repeated microscopy fields. The intact fruit body is boletoid, with a broad red to red-orange pileus, a poroid hymenophore, and a stout yellow to red-tinged stipe/base. No taxonomic identification is forced from these observations.",
    "Cap / Pileus": "Broad, convex to plano-convex, vivid red to red-orange with localized darker maroon to brownish spotting and minor surface abrasion. Margin is thick and slightly incurved to even in the field views.",
    "Hymenophore": "Poroid rather than lamellate. The fertile underside is composed of very small, dense pores; pore surface appears yellow-olive to brownish/olivaceous in the field photographs.",
    "Stem / Stipe": "Stipe is stout and centrally attached, yellow to yellow-orange with red to reddish-brown mottling and darker soil-stained basal tissue. Basal material retains adhering soil and organic debris.",
    "Base / Substrate": "Collected from forest-floor leaf litter with woody debris and soil. The basal portion retains dark soil and organic material, documenting direct ground/substrate association.",
    "Macro size": "No calibrated macroscopic dimensional record for AN2-F41 was found in the current measurements data. Macro dimensions are therefore not inferred from photographs.",
    "Spore-print color": "Pale gray-brown to light brown in the original source record; the 2026-10-01 foil preparation photographs show a clearly visible tan to light-brown deposit. Color is recorded descriptively and not used alone for identification.",
    "Spore shape": "Predominantly elongate, narrowly ellipsoid to fusiform, often somewhat inequilateral; ends are generally tapered to rounded. Spores occur singly and in local clusters. Wall outline appears smooth at this imaging level.",
    "Spore color / optical appearance": "Spores are translucent to pale yellow-brown / brownish in transmitted light, with darker internal contents visible in a subset of spores.",
    "Internal contents": "Several spores show a conspicuous dark, rounded internal body. This is a genuine repeated optical feature. It is recorded as a nucleus-like internal inclusion; nuclear identity is not considered independently confirmed without a nucleus-specific stain or fluorescence method.",
    "Spore measurements": "Three calibrated measurement fields contain 25 fully legible annotations. Six long-axis measurements: 9.80–13.23 µm, mean 11.49 µm, median 11.77 µm, sample SD 1.24 µm. Nineteen short-axis measurements: 3.04–4.74 µm, mean 3.84 µm, median 3.92 µm, sample SD 0.53 µm. The annotations are not consistently paired spore-by-spore, so a formal Q distribution is not calculated from this image set.",
    "Measurement values": "Long axis (µm): 11.74, 13.23, 11.79, 12.04, 9.80, 10.31. Short axis (µm): 3.05, 4.40, 4.40, 3.17, 3.45, 3.53, 4.29, 3.67, 4.74, 4.03, 4.30, 3.06, 3.92, 4.07, 3.04, 3.57, 4.42, 3.61, 4.15.",
    "Microscopy record": "Thirteen accession-linked AN2-F41 microscopy images are preserved. Three fields carry calibrated measurement annotations; the remaining fields document recurring morphology, abundance, clustering, focal variation, and internal optical features.",
    "Calibration / instrumentation": "Motic BA310 / Moticam 2300 imaging workflow. Quantitative transcription is limited to visible on-image calibrated annotations.",
    "Spore print / preparation": "The preparation series documents a substantial tan to light-brown deposit on aluminum foil and an accession-labeled AN2-F41 slide. Four preparation views from 2026-10-01 are retained in addition to the earlier AN2-F41SP.JPG source record.",
    "Record type": "Curated full-data SPM specimen record",
    "Identification status": "Taxonomic identification unresolved; morphology and measurements are preserved without forcing genus or species.",
    "Assignment rule": "Only explicit AN2-F41 accession-linked macro, spore-print, preparation, and microscopy records are used. No visual-similarity reassignment."
  },
  completeness: [
    ["Photo provenance","Yes"],
    ["Explicit specimen accession","Yes"],
    ["Wild / field imagery","Yes — 5 views"],
    ["Verified macro specimen imagery","Yes — 2 views"],
    ["Spore-print / preparation imagery","Yes — original source record + 4 new preparation views"],
    ["Microscopy imagery","Yes — 13 views"],
    ["Measured microscopy fields","Yes — 3"],
    ["Legible measurement annotations","25 total"],
    ["Long-axis measurements","6; 9.80–13.23 µm; mean 11.49 µm"],
    ["Short-axis measurements","19; 3.04–4.74 µm; mean 3.84 µm"],
    ["Spore shape documented","Yes — narrowly ellipsoid to fusiform, often inequilateral"],
    ["Spore-print color documented","Yes — pale gray-brown / tan to light brown"],
    ["Internal optical feature documented","Yes — repeated dark nucleus-like inclusion; identity not independently stain-confirmed"],
    ["Macro measurements","Not available — not inferred from images"],
    ["Successful microscopic spore record","Yes"],
    ["Field + laboratory pairing","Yes"],
    ["Identified","No — taxonomic identification unresolved"]
  ]
};

window.SPECIMEN_ENRICHMENTS["AN2-F1"] = {
  sourceLine: "AN2-F1 retains five accession-linked wild/field-context photographs and verified laboratory specimen views. Field images document the specimen on the forest floor. Laboratory macro photographs in this atlas were made with a Canon PowerShot SX20 IS. Microscopy imagery, when present for an accession, is acquired with a Motic BA310 microscope and Moticam 2300 camera using licensed Motic imaging/measurement software.",
  summary: {
    "Base / Substrate": "Documented in the accession-linked field photographs: specimen occurring on the forest ground layer in soil substrate among decomposing leaf litter / a decomposing leaf bed, with surrounding woodland organic debris. This field substrate is directly documented photographically and is not inferred from the laboratory view.",
    "Field context": "Confirmed forest-floor occurrence with soil substrate and decomposing leaf litter visible around the specimen.",
    "Laboratory imaging": "Laboratory macro photographs: Canon PowerShot SX20 IS.",
    "Microscopy instrumentation": "Atlas microscopy standard: Motic BA310 microscope with Moticam 2300 microscope camera and licensed Motic imaging/measurement software."
  },
  completeness: [
    ["Wild / field imagery","Yes — 5 accession-linked views"],
    ["Field substrate documented","Yes — soil on forest floor among decomposing leaf litter"],
    ["Laboratory camera provenance","Yes — Canon PowerShot SX20 IS"],
    ["Microscopy instrumentation documented","Yes — Motic BA310 + Moticam 2300"]
  ]
};
